package org.fc.wlt.ordbgens.wlt.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.outils.serialize.UUIDGenerator;

@AllArgsConstructor
@NoArgsConstructor
public class WLTAddrKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.ADDR_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String addrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.ADDR_ID
     *
     * @return the value of WLT_ADDR.ADDR_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.ADDR_ID
     *
     * @param addrId the value for WLT_ADDR.ADDR_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setAddrId(String addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTAddrKey other = (WLTAddrKey) that;
        return (this.getAddrId() == null ? other.getAddrId() == null : this.getAddrId().equals(other.getAddrId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAddrId() == null) ? 0 : getAddrId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", addrId=").append(addrId);
        sb.append("]");
        return sb.toString();
    }
}