package org.fc.wlt.ordbgens.wlt.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.outils.serialize.UUIDGenerator;

@AllArgsConstructor
@NoArgsConstructor
public class WLTAssetKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ASSET.ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String assetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ASSET.ASSET_ID
     *
     * @return the value of WLT_ASSET.ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getAssetId() {
        return assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ASSET.ASSET_ID
     *
     * @param assetId the value for WLT_ASSET.ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTAssetKey other = (WLTAssetKey) that;
        return (this.getAssetId() == null ? other.getAssetId() == null : this.getAssetId().equals(other.getAssetId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAssetId() == null) ? 0 : getAssetId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", assetId=").append(assetId);
        sb.append("]");
        return sb.toString();
    }
}