package org.fc.wlt.ordbgens.wlt.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="WLT_ADDR")
@AllArgsConstructor
@NoArgsConstructor
public class WLTAddr extends WLTAddrKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.HEX_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String hexAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.PUBLIC_KEY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String publicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.PUBLIC_KEY_HASH
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String publicKeyHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.PRIVATE_KEY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String privateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.ADDR_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String addrStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_ADDR.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.USER_ID
     *
     * @return the value of WLT_ADDR.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.USER_ID
     *
     * @param userId the value for WLT_ADDR.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.HEX_ADDR
     *
     * @return the value of WLT_ADDR.HEX_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getHexAddr() {
        return hexAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.HEX_ADDR
     *
     * @param hexAddr the value for WLT_ADDR.HEX_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setHexAddr(String hexAddr) {
        this.hexAddr = hexAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.PUBLIC_KEY
     *
     * @return the value of WLT_ADDR.PUBLIC_KEY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.PUBLIC_KEY
     *
     * @param publicKey the value for WLT_ADDR.PUBLIC_KEY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.PUBLIC_KEY_HASH
     *
     * @return the value of WLT_ADDR.PUBLIC_KEY_HASH
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getPublicKeyHash() {
        return publicKeyHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.PUBLIC_KEY_HASH
     *
     * @param publicKeyHash the value for WLT_ADDR.PUBLIC_KEY_HASH
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setPublicKeyHash(String publicKeyHash) {
        this.publicKeyHash = publicKeyHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.PRIVATE_KEY
     *
     * @return the value of WLT_ADDR.PRIVATE_KEY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.PRIVATE_KEY
     *
     * @param privateKey the value for WLT_ADDR.PRIVATE_KEY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.ADDR_STATUS
     *
     * @return the value of WLT_ADDR.ADDR_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getAddrStatus() {
        return addrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.ADDR_STATUS
     *
     * @param addrStatus the value for WLT_ADDR.ADDR_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setAddrStatus(String addrStatus) {
        this.addrStatus = addrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.CREATED_TIME
     *
     * @return the value of WLT_ADDR.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.CREATED_TIME
     *
     * @param createdTime the value for WLT_ADDR.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.UPDATED_TIME
     *
     * @return the value of WLT_ADDR.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.UPDATED_TIME
     *
     * @param updatedTime the value for WLT_ADDR.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.RESERVED1
     *
     * @return the value of WLT_ADDR.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.RESERVED1
     *
     * @param reserved1 the value for WLT_ADDR.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_ADDR.RESERVED2
     *
     * @return the value of WLT_ADDR.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_ADDR.RESERVED2
     *
     * @param reserved2 the value for WLT_ADDR.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTAddr other = (WLTAddr) that;
        return (this.getAddrId() == null ? other.getAddrId() == null : this.getAddrId().equals(other.getAddrId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getHexAddr() == null ? other.getHexAddr() == null : this.getHexAddr().equals(other.getHexAddr()))
            && (this.getPublicKey() == null ? other.getPublicKey() == null : this.getPublicKey().equals(other.getPublicKey()))
            && (this.getPublicKeyHash() == null ? other.getPublicKeyHash() == null : this.getPublicKeyHash().equals(other.getPublicKeyHash()))
            && (this.getPrivateKey() == null ? other.getPrivateKey() == null : this.getPrivateKey().equals(other.getPrivateKey()))
            && (this.getAddrStatus() == null ? other.getAddrStatus() == null : this.getAddrStatus().equals(other.getAddrStatus()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()))
            && (this.getReserved1() == null ? other.getReserved1() == null : this.getReserved1().equals(other.getReserved1()))
            && (this.getReserved2() == null ? other.getReserved2() == null : this.getReserved2().equals(other.getReserved2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAddrId() == null) ? 0 : getAddrId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getHexAddr() == null) ? 0 : getHexAddr().hashCode());
        result = prime * result + ((getPublicKey() == null) ? 0 : getPublicKey().hashCode());
        result = prime * result + ((getPublicKeyHash() == null) ? 0 : getPublicKeyHash().hashCode());
        result = prime * result + ((getPrivateKey() == null) ? 0 : getPrivateKey().hashCode());
        result = prime * result + ((getAddrStatus() == null) ? 0 : getAddrStatus().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        result = prime * result + ((getReserved1() == null) ? 0 : getReserved1().hashCode());
        result = prime * result + ((getReserved2() == null) ? 0 : getReserved2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", hexAddr=").append(hexAddr);
        sb.append(", publicKey=").append(publicKey);
        sb.append(", publicKeyHash=").append(publicKeyHash);
        sb.append(", privateKey=").append(privateKey);
        sb.append(", addrStatus=").append(addrStatus);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", reserved1=").append(reserved1);
        sb.append(", reserved2=").append(reserved2);
        sb.append("]");
        return sb.toString();
    }
}