package org.fc.wlt.ordbgens.wlt.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="WLT_CERT_PER")
@AllArgsConstructor
@NoArgsConstructor
public class WLTCertPer extends WLTCertPerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.PER_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String perCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.REAL_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.ID_CARD_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String idCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.ID_CARD_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String idCardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.ID_CARD_PHOTO_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String idCardPhotoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.PER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String perStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.UPDATED_TIMD
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Date updatedTimd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_PER.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.PER_CODE
     *
     * @return the value of WLT_CERT_PER.PER_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getPerCode() {
        return perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.PER_CODE
     *
     * @param perCode the value for WLT_CERT_PER.PER_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setPerCode(String perCode) {
        this.perCode = perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.USER_ID
     *
     * @return the value of WLT_CERT_PER.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.USER_ID
     *
     * @param userId the value for WLT_CERT_PER.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.REAL_NAME
     *
     * @return the value of WLT_CERT_PER.REAL_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.REAL_NAME
     *
     * @param realName the value for WLT_CERT_PER.REAL_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.ID_CARD_TYPE
     *
     * @return the value of WLT_CERT_PER.ID_CARD_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getIdCardType() {
        return idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.ID_CARD_TYPE
     *
     * @param idCardType the value for WLT_CERT_PER.ID_CARD_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setIdCardType(String idCardType) {
        this.idCardType = idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.ID_CARD_CODE
     *
     * @return the value of WLT_CERT_PER.ID_CARD_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getIdCardCode() {
        return idCardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.ID_CARD_CODE
     *
     * @param idCardCode the value for WLT_CERT_PER.ID_CARD_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setIdCardCode(String idCardCode) {
        this.idCardCode = idCardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.ID_CARD_PHOTO_ID
     *
     * @return the value of WLT_CERT_PER.ID_CARD_PHOTO_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getIdCardPhotoId() {
        return idCardPhotoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.ID_CARD_PHOTO_ID
     *
     * @param idCardPhotoId the value for WLT_CERT_PER.ID_CARD_PHOTO_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setIdCardPhotoId(String idCardPhotoId) {
        this.idCardPhotoId = idCardPhotoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.PER_STATUS
     *
     * @return the value of WLT_CERT_PER.PER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getPerStatus() {
        return perStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.PER_STATUS
     *
     * @param perStatus the value for WLT_CERT_PER.PER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setPerStatus(String perStatus) {
        this.perStatus = perStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.CREATED_TIME
     *
     * @return the value of WLT_CERT_PER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.CREATED_TIME
     *
     * @param createdTime the value for WLT_CERT_PER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.UPDATED_TIMD
     *
     * @return the value of WLT_CERT_PER.UPDATED_TIMD
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Date getUpdatedTimd() {
        return updatedTimd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.UPDATED_TIMD
     *
     * @param updatedTimd the value for WLT_CERT_PER.UPDATED_TIMD
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setUpdatedTimd(Date updatedTimd) {
        this.updatedTimd = updatedTimd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.RESERVED1
     *
     * @return the value of WLT_CERT_PER.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.RESERVED1
     *
     * @param reserved1 the value for WLT_CERT_PER.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_PER.RESERVED2
     *
     * @return the value of WLT_CERT_PER.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_PER.RESERVED2
     *
     * @param reserved2 the value for WLT_CERT_PER.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTCertPer other = (WLTCertPer) that;
        return (this.getPerId() == null ? other.getPerId() == null : this.getPerId().equals(other.getPerId()))
            && (this.getPerCode() == null ? other.getPerCode() == null : this.getPerCode().equals(other.getPerCode()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))
            && (this.getIdCardType() == null ? other.getIdCardType() == null : this.getIdCardType().equals(other.getIdCardType()))
            && (this.getIdCardCode() == null ? other.getIdCardCode() == null : this.getIdCardCode().equals(other.getIdCardCode()))
            && (this.getIdCardPhotoId() == null ? other.getIdCardPhotoId() == null : this.getIdCardPhotoId().equals(other.getIdCardPhotoId()))
            && (this.getPerStatus() == null ? other.getPerStatus() == null : this.getPerStatus().equals(other.getPerStatus()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTimd() == null ? other.getUpdatedTimd() == null : this.getUpdatedTimd().equals(other.getUpdatedTimd()))
            && (this.getReserved1() == null ? other.getReserved1() == null : this.getReserved1().equals(other.getReserved1()))
            && (this.getReserved2() == null ? other.getReserved2() == null : this.getReserved2().equals(other.getReserved2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPerId() == null) ? 0 : getPerId().hashCode());
        result = prime * result + ((getPerCode() == null) ? 0 : getPerCode().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
        result = prime * result + ((getIdCardType() == null) ? 0 : getIdCardType().hashCode());
        result = prime * result + ((getIdCardCode() == null) ? 0 : getIdCardCode().hashCode());
        result = prime * result + ((getIdCardPhotoId() == null) ? 0 : getIdCardPhotoId().hashCode());
        result = prime * result + ((getPerStatus() == null) ? 0 : getPerStatus().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTimd() == null) ? 0 : getUpdatedTimd().hashCode());
        result = prime * result + ((getReserved1() == null) ? 0 : getReserved1().hashCode());
        result = prime * result + ((getReserved2() == null) ? 0 : getReserved2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", perCode=").append(perCode);
        sb.append(", userId=").append(userId);
        sb.append(", realName=").append(realName);
        sb.append(", idCardType=").append(idCardType);
        sb.append(", idCardCode=").append(idCardCode);
        sb.append(", idCardPhotoId=").append(idCardPhotoId);
        sb.append(", perStatus=").append(perStatus);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTimd=").append(updatedTimd);
        sb.append(", reserved1=").append(reserved1);
        sb.append(", reserved2=").append(reserved2);
        sb.append("]");
        return sb.toString();
    }
}