package org.fc.wlt.ordbgens.wlt.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class WLTCertPerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected boolean forUpdate;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public WLTCertPerExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
        this.forUpdate=false;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setForUpdate(boolean forUpdate) {
         this.forUpdate = forUpdate;
    }

    public boolean isForUpdate() {
          return forUpdate;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPerIdIsNull() {
            addCriterion("PER_ID is null");
            return (Criteria) this;
        }

        public Criteria andPerIdIsNotNull() {
            addCriterion("PER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPerIdEqualTo(String value) {
            addCriterion("PER_ID =", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotEqualTo(String value) {
            addCriterion("PER_ID <>", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdGreaterThan(String value) {
            addCriterion("PER_ID >", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdGreaterThanOrEqualTo(String value) {
            addCriterion("PER_ID >=", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLessThan(String value) {
            addCriterion("PER_ID <", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLessThanOrEqualTo(String value) {
            addCriterion("PER_ID <=", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLike(String value) {
            addCriterion("PER_ID like", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotLike(String value) {
            addCriterion("PER_ID not like", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdIn(List<String> values) {
            addCriterion("PER_ID in", values, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotIn(List<String> values) {
            addCriterion("PER_ID not in", values, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdBetween(String value1, String value2) {
            addCriterion("PER_ID between", value1, value2, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotBetween(String value1, String value2) {
            addCriterion("PER_ID not between", value1, value2, "perId");
            return (Criteria) this;
        }

        public Criteria andPerCodeIsNull() {
            addCriterion("PER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPerCodeIsNotNull() {
            addCriterion("PER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPerCodeEqualTo(String value) {
            addCriterion("PER_CODE =", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeNotEqualTo(String value) {
            addCriterion("PER_CODE <>", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeGreaterThan(String value) {
            addCriterion("PER_CODE >", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PER_CODE >=", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeLessThan(String value) {
            addCriterion("PER_CODE <", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeLessThanOrEqualTo(String value) {
            addCriterion("PER_CODE <=", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeLike(String value) {
            addCriterion("PER_CODE like", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeNotLike(String value) {
            addCriterion("PER_CODE not like", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeIn(List<String> values) {
            addCriterion("PER_CODE in", values, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeNotIn(List<String> values) {
            addCriterion("PER_CODE not in", values, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeBetween(String value1, String value2) {
            addCriterion("PER_CODE between", value1, value2, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeNotBetween(String value1, String value2) {
            addCriterion("PER_CODE not between", value1, value2, "perCode");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("REAL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("REAL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("REAL_NAME =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("REAL_NAME <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("REAL_NAME >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("REAL_NAME >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("REAL_NAME <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("REAL_NAME <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("REAL_NAME like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("REAL_NAME not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("REAL_NAME in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("REAL_NAME not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("REAL_NAME between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("REAL_NAME not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeIsNull() {
            addCriterion("ID_CARD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeIsNotNull() {
            addCriterion("ID_CARD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeEqualTo(String value) {
            addCriterion("ID_CARD_TYPE =", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeNotEqualTo(String value) {
            addCriterion("ID_CARD_TYPE <>", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeGreaterThan(String value) {
            addCriterion("ID_CARD_TYPE >", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CARD_TYPE >=", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeLessThan(String value) {
            addCriterion("ID_CARD_TYPE <", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeLessThanOrEqualTo(String value) {
            addCriterion("ID_CARD_TYPE <=", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeLike(String value) {
            addCriterion("ID_CARD_TYPE like", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeNotLike(String value) {
            addCriterion("ID_CARD_TYPE not like", value, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeIn(List<String> values) {
            addCriterion("ID_CARD_TYPE in", values, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeNotIn(List<String> values) {
            addCriterion("ID_CARD_TYPE not in", values, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeBetween(String value1, String value2) {
            addCriterion("ID_CARD_TYPE between", value1, value2, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeNotBetween(String value1, String value2) {
            addCriterion("ID_CARD_TYPE not between", value1, value2, "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeIsNull() {
            addCriterion("ID_CARD_CODE is null");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeIsNotNull() {
            addCriterion("ID_CARD_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeEqualTo(String value) {
            addCriterion("ID_CARD_CODE =", value, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeNotEqualTo(String value) {
            addCriterion("ID_CARD_CODE <>", value, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeGreaterThan(String value) {
            addCriterion("ID_CARD_CODE >", value, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CARD_CODE >=", value, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeLessThan(String value) {
            addCriterion("ID_CARD_CODE <", value, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeLessThanOrEqualTo(String value) {
            addCriterion("ID_CARD_CODE <=", value, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeLike(String value) {
            addCriterion("ID_CARD_CODE like", value, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeNotLike(String value) {
            addCriterion("ID_CARD_CODE not like", value, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeIn(List<String> values) {
            addCriterion("ID_CARD_CODE in", values, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeNotIn(List<String> values) {
            addCriterion("ID_CARD_CODE not in", values, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeBetween(String value1, String value2) {
            addCriterion("ID_CARD_CODE between", value1, value2, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeNotBetween(String value1, String value2) {
            addCriterion("ID_CARD_CODE not between", value1, value2, "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdIsNull() {
            addCriterion("ID_CARD_PHOTO_ID is null");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdIsNotNull() {
            addCriterion("ID_CARD_PHOTO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdEqualTo(String value) {
            addCriterion("ID_CARD_PHOTO_ID =", value, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdNotEqualTo(String value) {
            addCriterion("ID_CARD_PHOTO_ID <>", value, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdGreaterThan(String value) {
            addCriterion("ID_CARD_PHOTO_ID >", value, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CARD_PHOTO_ID >=", value, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdLessThan(String value) {
            addCriterion("ID_CARD_PHOTO_ID <", value, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdLessThanOrEqualTo(String value) {
            addCriterion("ID_CARD_PHOTO_ID <=", value, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdLike(String value) {
            addCriterion("ID_CARD_PHOTO_ID like", value, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdNotLike(String value) {
            addCriterion("ID_CARD_PHOTO_ID not like", value, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdIn(List<String> values) {
            addCriterion("ID_CARD_PHOTO_ID in", values, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdNotIn(List<String> values) {
            addCriterion("ID_CARD_PHOTO_ID not in", values, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdBetween(String value1, String value2) {
            addCriterion("ID_CARD_PHOTO_ID between", value1, value2, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdNotBetween(String value1, String value2) {
            addCriterion("ID_CARD_PHOTO_ID not between", value1, value2, "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andPerStatusIsNull() {
            addCriterion("PER_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andPerStatusIsNotNull() {
            addCriterion("PER_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andPerStatusEqualTo(String value) {
            addCriterion("PER_STATUS =", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotEqualTo(String value) {
            addCriterion("PER_STATUS <>", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusGreaterThan(String value) {
            addCriterion("PER_STATUS >", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusGreaterThanOrEqualTo(String value) {
            addCriterion("PER_STATUS >=", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusLessThan(String value) {
            addCriterion("PER_STATUS <", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusLessThanOrEqualTo(String value) {
            addCriterion("PER_STATUS <=", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusLike(String value) {
            addCriterion("PER_STATUS like", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotLike(String value) {
            addCriterion("PER_STATUS not like", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusIn(List<String> values) {
            addCriterion("PER_STATUS in", values, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotIn(List<String> values) {
            addCriterion("PER_STATUS not in", values, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusBetween(String value1, String value2) {
            addCriterion("PER_STATUS between", value1, value2, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotBetween(String value1, String value2) {
            addCriterion("PER_STATUS not between", value1, value2, "perStatus");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdIsNull() {
            addCriterion("UPDATED_TIMD is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdIsNotNull() {
            addCriterion("UPDATED_TIMD is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdEqualTo(Date value) {
            addCriterion("UPDATED_TIMD =", value, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdNotEqualTo(Date value) {
            addCriterion("UPDATED_TIMD <>", value, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdGreaterThan(Date value) {
            addCriterion("UPDATED_TIMD >", value, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_TIMD >=", value, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdLessThan(Date value) {
            addCriterion("UPDATED_TIMD <", value, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_TIMD <=", value, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdIn(List<Date> values) {
            addCriterion("UPDATED_TIMD in", values, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdNotIn(List<Date> values) {
            addCriterion("UPDATED_TIMD not in", values, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdBetween(Date value1, Date value2) {
            addCriterion("UPDATED_TIMD between", value1, value2, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimdNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_TIMD not between", value1, value2, "updatedTimd");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNull() {
            addCriterion("RESERVED1 is null");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNotNull() {
            addCriterion("RESERVED1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved1EqualTo(String value) {
            addCriterion("RESERVED1 =", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotEqualTo(String value) {
            addCriterion("RESERVED1 <>", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThan(String value) {
            addCriterion("RESERVED1 >", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVED1 >=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThan(String value) {
            addCriterion("RESERVED1 <", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThanOrEqualTo(String value) {
            addCriterion("RESERVED1 <=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Like(String value) {
            addCriterion("RESERVED1 like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotLike(String value) {
            addCriterion("RESERVED1 not like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1In(List<String> values) {
            addCriterion("RESERVED1 in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotIn(List<String> values) {
            addCriterion("RESERVED1 not in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Between(String value1, String value2) {
            addCriterion("RESERVED1 between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotBetween(String value1, String value2) {
            addCriterion("RESERVED1 not between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNull() {
            addCriterion("RESERVED2 is null");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNotNull() {
            addCriterion("RESERVED2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved2EqualTo(String value) {
            addCriterion("RESERVED2 =", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotEqualTo(String value) {
            addCriterion("RESERVED2 <>", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThan(String value) {
            addCriterion("RESERVED2 >", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVED2 >=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThan(String value) {
            addCriterion("RESERVED2 <", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThanOrEqualTo(String value) {
            addCriterion("RESERVED2 <=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Like(String value) {
            addCriterion("RESERVED2 like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotLike(String value) {
            addCriterion("RESERVED2 not like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2In(List<String> values) {
            addCriterion("RESERVED2 in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotIn(List<String> values) {
            addCriterion("RESERVED2 not in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Between(String value1, String value2) {
            addCriterion("RESERVED2 between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotBetween(String value1, String value2) {
            addCriterion("RESERVED2 not between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andPerIdLikeInsensitive(String value) {
            addCriterion("upper(PER_ID) like", value.toUpperCase(), "perId");
            return (Criteria) this;
        }

        public Criteria andPerCodeLikeInsensitive(String value) {
            addCriterion("upper(PER_CODE) like", value.toUpperCase(), "perCode");
            return (Criteria) this;
        }

        public Criteria andUserIdLikeInsensitive(String value) {
            addCriterion("upper(USER_ID) like", value.toUpperCase(), "userId");
            return (Criteria) this;
        }

        public Criteria andRealNameLikeInsensitive(String value) {
            addCriterion("upper(REAL_NAME) like", value.toUpperCase(), "realName");
            return (Criteria) this;
        }

        public Criteria andIdCardTypeLikeInsensitive(String value) {
            addCriterion("upper(ID_CARD_TYPE) like", value.toUpperCase(), "idCardType");
            return (Criteria) this;
        }

        public Criteria andIdCardCodeLikeInsensitive(String value) {
            addCriterion("upper(ID_CARD_CODE) like", value.toUpperCase(), "idCardCode");
            return (Criteria) this;
        }

        public Criteria andIdCardPhotoIdLikeInsensitive(String value) {
            addCriterion("upper(ID_CARD_PHOTO_ID) like", value.toUpperCase(), "idCardPhotoId");
            return (Criteria) this;
        }

        public Criteria andPerStatusLikeInsensitive(String value) {
            addCriterion("upper(PER_STATUS) like", value.toUpperCase(), "perStatus");
            return (Criteria) this;
        }

        public Criteria andReserved1LikeInsensitive(String value) {
            addCriterion("upper(RESERVED1) like", value.toUpperCase(), "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2LikeInsensitive(String value) {
            addCriterion("upper(RESERVED2) like", value.toUpperCase(), "reserved2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 01 14:31:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}