package org.fc.wlt.ordbgens.wlt.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="WLT_CERT_ORG")
@AllArgsConstructor
@NoArgsConstructor
public class WLTCertOrg extends WLTCertOrgKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.ORG_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.ORG_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.ORG_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.CORPORATE_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String corporateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.LICENSE_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String licenseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.LICENSE_PHOTO_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String licensePhotoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.NATIONAL
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String national;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.PROVINCE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.CITY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.STREET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.TEL
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.FAX
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.WEB_RECORD_NUM
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String webRecordNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.ORG_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String orgStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_CERT_ORG.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.ORG_CODE
     *
     * @return the value of WLT_CERT_ORG.ORG_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.ORG_CODE
     *
     * @param orgCode the value for WLT_CERT_ORG.ORG_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.ORG_NAME
     *
     * @return the value of WLT_CERT_ORG.ORG_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.ORG_NAME
     *
     * @param orgName the value for WLT_CERT_ORG.ORG_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.ORG_TYPE
     *
     * @return the value of WLT_CERT_ORG.ORG_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.ORG_TYPE
     *
     * @param orgType the value for WLT_CERT_ORG.ORG_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.USER_ID
     *
     * @return the value of WLT_CERT_ORG.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.USER_ID
     *
     * @param userId the value for WLT_CERT_ORG.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.CORPORATE_NAME
     *
     * @return the value of WLT_CERT_ORG.CORPORATE_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getCorporateName() {
        return corporateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.CORPORATE_NAME
     *
     * @param corporateName the value for WLT_CERT_ORG.CORPORATE_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setCorporateName(String corporateName) {
        this.corporateName = corporateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.LICENSE_CODE
     *
     * @return the value of WLT_CERT_ORG.LICENSE_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getLicenseCode() {
        return licenseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.LICENSE_CODE
     *
     * @param licenseCode the value for WLT_CERT_ORG.LICENSE_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setLicenseCode(String licenseCode) {
        this.licenseCode = licenseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.LICENSE_PHOTO_ID
     *
     * @return the value of WLT_CERT_ORG.LICENSE_PHOTO_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getLicensePhotoId() {
        return licensePhotoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.LICENSE_PHOTO_ID
     *
     * @param licensePhotoId the value for WLT_CERT_ORG.LICENSE_PHOTO_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setLicensePhotoId(String licensePhotoId) {
        this.licensePhotoId = licensePhotoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.NATIONAL
     *
     * @return the value of WLT_CERT_ORG.NATIONAL
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getNational() {
        return national;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.NATIONAL
     *
     * @param national the value for WLT_CERT_ORG.NATIONAL
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setNational(String national) {
        this.national = national;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.PROVINCE
     *
     * @return the value of WLT_CERT_ORG.PROVINCE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.PROVINCE
     *
     * @param province the value for WLT_CERT_ORG.PROVINCE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.CITY
     *
     * @return the value of WLT_CERT_ORG.CITY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.CITY
     *
     * @param city the value for WLT_CERT_ORG.CITY
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.STREET
     *
     * @return the value of WLT_CERT_ORG.STREET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.STREET
     *
     * @param street the value for WLT_CERT_ORG.STREET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.TEL
     *
     * @return the value of WLT_CERT_ORG.TEL
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.TEL
     *
     * @param tel the value for WLT_CERT_ORG.TEL
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.FAX
     *
     * @return the value of WLT_CERT_ORG.FAX
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.FAX
     *
     * @param fax the value for WLT_CERT_ORG.FAX
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.WEB_RECORD_NUM
     *
     * @return the value of WLT_CERT_ORG.WEB_RECORD_NUM
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getWebRecordNum() {
        return webRecordNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.WEB_RECORD_NUM
     *
     * @param webRecordNum the value for WLT_CERT_ORG.WEB_RECORD_NUM
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setWebRecordNum(String webRecordNum) {
        this.webRecordNum = webRecordNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.ORG_STATUS
     *
     * @return the value of WLT_CERT_ORG.ORG_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getOrgStatus() {
        return orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.ORG_STATUS
     *
     * @param orgStatus the value for WLT_CERT_ORG.ORG_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setOrgStatus(String orgStatus) {
        this.orgStatus = orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.CREATED_TIME
     *
     * @return the value of WLT_CERT_ORG.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.CREATED_TIME
     *
     * @param createdTime the value for WLT_CERT_ORG.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.UPDATED_TIME
     *
     * @return the value of WLT_CERT_ORG.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.UPDATED_TIME
     *
     * @param updatedTime the value for WLT_CERT_ORG.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.RESERVED1
     *
     * @return the value of WLT_CERT_ORG.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.RESERVED1
     *
     * @param reserved1 the value for WLT_CERT_ORG.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_CERT_ORG.RESERVED2
     *
     * @return the value of WLT_CERT_ORG.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_CERT_ORG.RESERVED2
     *
     * @param reserved2 the value for WLT_CERT_ORG.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTCertOrg other = (WLTCertOrg) that;
        return (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getOrgType() == null ? other.getOrgType() == null : this.getOrgType().equals(other.getOrgType()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCorporateName() == null ? other.getCorporateName() == null : this.getCorporateName().equals(other.getCorporateName()))
            && (this.getLicenseCode() == null ? other.getLicenseCode() == null : this.getLicenseCode().equals(other.getLicenseCode()))
            && (this.getLicensePhotoId() == null ? other.getLicensePhotoId() == null : this.getLicensePhotoId().equals(other.getLicensePhotoId()))
            && (this.getNational() == null ? other.getNational() == null : this.getNational().equals(other.getNational()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getStreet() == null ? other.getStreet() == null : this.getStreet().equals(other.getStreet()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getWebRecordNum() == null ? other.getWebRecordNum() == null : this.getWebRecordNum().equals(other.getWebRecordNum()))
            && (this.getOrgStatus() == null ? other.getOrgStatus() == null : this.getOrgStatus().equals(other.getOrgStatus()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()))
            && (this.getReserved1() == null ? other.getReserved1() == null : this.getReserved1().equals(other.getReserved1()))
            && (this.getReserved2() == null ? other.getReserved2() == null : this.getReserved2().equals(other.getReserved2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getOrgType() == null) ? 0 : getOrgType().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCorporateName() == null) ? 0 : getCorporateName().hashCode());
        result = prime * result + ((getLicenseCode() == null) ? 0 : getLicenseCode().hashCode());
        result = prime * result + ((getLicensePhotoId() == null) ? 0 : getLicensePhotoId().hashCode());
        result = prime * result + ((getNational() == null) ? 0 : getNational().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getStreet() == null) ? 0 : getStreet().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getWebRecordNum() == null) ? 0 : getWebRecordNum().hashCode());
        result = prime * result + ((getOrgStatus() == null) ? 0 : getOrgStatus().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        result = prime * result + ((getReserved1() == null) ? 0 : getReserved1().hashCode());
        result = prime * result + ((getReserved2() == null) ? 0 : getReserved2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orgCode=").append(orgCode);
        sb.append(", orgName=").append(orgName);
        sb.append(", orgType=").append(orgType);
        sb.append(", userId=").append(userId);
        sb.append(", corporateName=").append(corporateName);
        sb.append(", licenseCode=").append(licenseCode);
        sb.append(", licensePhotoId=").append(licensePhotoId);
        sb.append(", national=").append(national);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", street=").append(street);
        sb.append(", tel=").append(tel);
        sb.append(", fax=").append(fax);
        sb.append(", webRecordNum=").append(webRecordNum);
        sb.append(", orgStatus=").append(orgStatus);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", reserved1=").append(reserved1);
        sb.append(", reserved2=").append(reserved2);
        sb.append("]");
        return sb.toString();
    }
}