package org.fc.wlt.ordbgens.wlt.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class WLTFundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected boolean forUpdate;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public WLTFundExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
        this.forUpdate=false;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setForUpdate(boolean forUpdate) {
         this.forUpdate = forUpdate;
    }

    public boolean isForUpdate() {
          return forUpdate;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFundIdIsNull() {
            addCriterion("FUND_ID is null");
            return (Criteria) this;
        }

        public Criteria andFundIdIsNotNull() {
            addCriterion("FUND_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFundIdEqualTo(String value) {
            addCriterion("FUND_ID =", value, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdNotEqualTo(String value) {
            addCriterion("FUND_ID <>", value, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdGreaterThan(String value) {
            addCriterion("FUND_ID >", value, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdGreaterThanOrEqualTo(String value) {
            addCriterion("FUND_ID >=", value, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdLessThan(String value) {
            addCriterion("FUND_ID <", value, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdLessThanOrEqualTo(String value) {
            addCriterion("FUND_ID <=", value, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdLike(String value) {
            addCriterion("FUND_ID like", value, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdNotLike(String value) {
            addCriterion("FUND_ID not like", value, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdIn(List<String> values) {
            addCriterion("FUND_ID in", values, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdNotIn(List<String> values) {
            addCriterion("FUND_ID not in", values, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdBetween(String value1, String value2) {
            addCriterion("FUND_ID between", value1, value2, "fundId");
            return (Criteria) this;
        }

        public Criteria andFundIdNotBetween(String value1, String value2) {
            addCriterion("FUND_ID not between", value1, value2, "fundId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andDmtCnameIsNull() {
            addCriterion("DMT_CNAME is null");
            return (Criteria) this;
        }

        public Criteria andDmtCnameIsNotNull() {
            addCriterion("DMT_CNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDmtCnameEqualTo(String value) {
            addCriterion("DMT_CNAME =", value, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameNotEqualTo(String value) {
            addCriterion("DMT_CNAME <>", value, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameGreaterThan(String value) {
            addCriterion("DMT_CNAME >", value, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameGreaterThanOrEqualTo(String value) {
            addCriterion("DMT_CNAME >=", value, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameLessThan(String value) {
            addCriterion("DMT_CNAME <", value, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameLessThanOrEqualTo(String value) {
            addCriterion("DMT_CNAME <=", value, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameLike(String value) {
            addCriterion("DMT_CNAME like", value, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameNotLike(String value) {
            addCriterion("DMT_CNAME not like", value, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameIn(List<String> values) {
            addCriterion("DMT_CNAME in", values, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameNotIn(List<String> values) {
            addCriterion("DMT_CNAME not in", values, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameBetween(String value1, String value2) {
            addCriterion("DMT_CNAME between", value1, value2, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtCnameNotBetween(String value1, String value2) {
            addCriterion("DMT_CNAME not between", value1, value2, "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameIsNull() {
            addCriterion("DMT_ENAME is null");
            return (Criteria) this;
        }

        public Criteria andDmtEnameIsNotNull() {
            addCriterion("DMT_ENAME is not null");
            return (Criteria) this;
        }

        public Criteria andDmtEnameEqualTo(String value) {
            addCriterion("DMT_ENAME =", value, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameNotEqualTo(String value) {
            addCriterion("DMT_ENAME <>", value, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameGreaterThan(String value) {
            addCriterion("DMT_ENAME >", value, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameGreaterThanOrEqualTo(String value) {
            addCriterion("DMT_ENAME >=", value, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameLessThan(String value) {
            addCriterion("DMT_ENAME <", value, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameLessThanOrEqualTo(String value) {
            addCriterion("DMT_ENAME <=", value, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameLike(String value) {
            addCriterion("DMT_ENAME like", value, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameNotLike(String value) {
            addCriterion("DMT_ENAME not like", value, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameIn(List<String> values) {
            addCriterion("DMT_ENAME in", values, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameNotIn(List<String> values) {
            addCriterion("DMT_ENAME not in", values, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameBetween(String value1, String value2) {
            addCriterion("DMT_ENAME between", value1, value2, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameNotBetween(String value1, String value2) {
            addCriterion("DMT_ENAME not between", value1, value2, "dmtEname");
            return (Criteria) this;
        }

        public Criteria andGenisAddrIsNull() {
            addCriterion("GENIS_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andGenisAddrIsNotNull() {
            addCriterion("GENIS_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andGenisAddrEqualTo(String value) {
            addCriterion("GENIS_ADDR =", value, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrNotEqualTo(String value) {
            addCriterion("GENIS_ADDR <>", value, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrGreaterThan(String value) {
            addCriterion("GENIS_ADDR >", value, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrGreaterThanOrEqualTo(String value) {
            addCriterion("GENIS_ADDR >=", value, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrLessThan(String value) {
            addCriterion("GENIS_ADDR <", value, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrLessThanOrEqualTo(String value) {
            addCriterion("GENIS_ADDR <=", value, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrLike(String value) {
            addCriterion("GENIS_ADDR like", value, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrNotLike(String value) {
            addCriterion("GENIS_ADDR not like", value, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrIn(List<String> values) {
            addCriterion("GENIS_ADDR in", values, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrNotIn(List<String> values) {
            addCriterion("GENIS_ADDR not in", values, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrBetween(String value1, String value2) {
            addCriterion("GENIS_ADDR between", value1, value2, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisAddrNotBetween(String value1, String value2) {
            addCriterion("GENIS_ADDR not between", value1, value2, "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdIsNull() {
            addCriterion("GENIS_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdIsNotNull() {
            addCriterion("GENIS_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdEqualTo(String value) {
            addCriterion("GENIS_ORG_ID =", value, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdNotEqualTo(String value) {
            addCriterion("GENIS_ORG_ID <>", value, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdGreaterThan(String value) {
            addCriterion("GENIS_ORG_ID >", value, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("GENIS_ORG_ID >=", value, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdLessThan(String value) {
            addCriterion("GENIS_ORG_ID <", value, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdLessThanOrEqualTo(String value) {
            addCriterion("GENIS_ORG_ID <=", value, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdLike(String value) {
            addCriterion("GENIS_ORG_ID like", value, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdNotLike(String value) {
            addCriterion("GENIS_ORG_ID not like", value, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdIn(List<String> values) {
            addCriterion("GENIS_ORG_ID in", values, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdNotIn(List<String> values) {
            addCriterion("GENIS_ORG_ID not in", values, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdBetween(String value1, String value2) {
            addCriterion("GENIS_ORG_ID between", value1, value2, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdNotBetween(String value1, String value2) {
            addCriterion("GENIS_ORG_ID not between", value1, value2, "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andGenisDepositIsNull() {
            addCriterion("GENIS_DEPOSIT is null");
            return (Criteria) this;
        }

        public Criteria andGenisDepositIsNotNull() {
            addCriterion("GENIS_DEPOSIT is not null");
            return (Criteria) this;
        }

        public Criteria andGenisDepositEqualTo(Double value) {
            addCriterion("GENIS_DEPOSIT =", value, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositNotEqualTo(Double value) {
            addCriterion("GENIS_DEPOSIT <>", value, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositGreaterThan(Double value) {
            addCriterion("GENIS_DEPOSIT >", value, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositGreaterThanOrEqualTo(Double value) {
            addCriterion("GENIS_DEPOSIT >=", value, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositLessThan(Double value) {
            addCriterion("GENIS_DEPOSIT <", value, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositLessThanOrEqualTo(Double value) {
            addCriterion("GENIS_DEPOSIT <=", value, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositIn(List<Double> values) {
            addCriterion("GENIS_DEPOSIT in", values, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositNotIn(List<Double> values) {
            addCriterion("GENIS_DEPOSIT not in", values, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositBetween(Double value1, Double value2) {
            addCriterion("GENIS_DEPOSIT between", value1, value2, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andGenisDepositNotBetween(Double value1, Double value2) {
            addCriterion("GENIS_DEPOSIT not between", value1, value2, "genisDeposit");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNull() {
            addCriterion("TOTAL_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNotNull() {
            addCriterion("TOTAL_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCountEqualTo(Double value) {
            addCriterion("TOTAL_COUNT =", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotEqualTo(Double value) {
            addCriterion("TOTAL_COUNT <>", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThan(Double value) {
            addCriterion("TOTAL_COUNT >", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThanOrEqualTo(Double value) {
            addCriterion("TOTAL_COUNT >=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThan(Double value) {
            addCriterion("TOTAL_COUNT <", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThanOrEqualTo(Double value) {
            addCriterion("TOTAL_COUNT <=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountIn(List<Double> values) {
            addCriterion("TOTAL_COUNT in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotIn(List<Double> values) {
            addCriterion("TOTAL_COUNT not in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountBetween(Double value1, Double value2) {
            addCriterion("TOTAL_COUNT between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotBetween(Double value1, Double value2) {
            addCriterion("TOTAL_COUNT not between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andColoredFbcIsNull() {
            addCriterion("COLORED_FBC is null");
            return (Criteria) this;
        }

        public Criteria andColoredFbcIsNotNull() {
            addCriterion("COLORED_FBC is not null");
            return (Criteria) this;
        }

        public Criteria andColoredFbcEqualTo(Double value) {
            addCriterion("COLORED_FBC =", value, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcNotEqualTo(Double value) {
            addCriterion("COLORED_FBC <>", value, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcGreaterThan(Double value) {
            addCriterion("COLORED_FBC >", value, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcGreaterThanOrEqualTo(Double value) {
            addCriterion("COLORED_FBC >=", value, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcLessThan(Double value) {
            addCriterion("COLORED_FBC <", value, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcLessThanOrEqualTo(Double value) {
            addCriterion("COLORED_FBC <=", value, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcIn(List<Double> values) {
            addCriterion("COLORED_FBC in", values, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcNotIn(List<Double> values) {
            addCriterion("COLORED_FBC not in", values, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcBetween(Double value1, Double value2) {
            addCriterion("COLORED_FBC between", value1, value2, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andColoredFbcNotBetween(Double value1, Double value2) {
            addCriterion("COLORED_FBC not between", value1, value2, "coloredFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcIsNull() {
            addCriterion("EXCHANGE_FBC is null");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcIsNotNull() {
            addCriterion("EXCHANGE_FBC is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcEqualTo(Double value) {
            addCriterion("EXCHANGE_FBC =", value, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcNotEqualTo(Double value) {
            addCriterion("EXCHANGE_FBC <>", value, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcGreaterThan(Double value) {
            addCriterion("EXCHANGE_FBC >", value, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcGreaterThanOrEqualTo(Double value) {
            addCriterion("EXCHANGE_FBC >=", value, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcLessThan(Double value) {
            addCriterion("EXCHANGE_FBC <", value, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcLessThanOrEqualTo(Double value) {
            addCriterion("EXCHANGE_FBC <=", value, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcIn(List<Double> values) {
            addCriterion("EXCHANGE_FBC in", values, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcNotIn(List<Double> values) {
            addCriterion("EXCHANGE_FBC not in", values, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcBetween(Double value1, Double value2) {
            addCriterion("EXCHANGE_FBC between", value1, value2, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andExchangeFbcNotBetween(Double value1, Double value2) {
            addCriterion("EXCHANGE_FBC not between", value1, value2, "exchangeFbc");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountIsNull() {
            addCriterion("TURNOVER_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountIsNotNull() {
            addCriterion("TURNOVER_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountEqualTo(Double value) {
            addCriterion("TURNOVER_COUNT =", value, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountNotEqualTo(Double value) {
            addCriterion("TURNOVER_COUNT <>", value, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountGreaterThan(Double value) {
            addCriterion("TURNOVER_COUNT >", value, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountGreaterThanOrEqualTo(Double value) {
            addCriterion("TURNOVER_COUNT >=", value, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountLessThan(Double value) {
            addCriterion("TURNOVER_COUNT <", value, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountLessThanOrEqualTo(Double value) {
            addCriterion("TURNOVER_COUNT <=", value, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountIn(List<Double> values) {
            addCriterion("TURNOVER_COUNT in", values, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountNotIn(List<Double> values) {
            addCriterion("TURNOVER_COUNT not in", values, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountBetween(Double value1, Double value2) {
            addCriterion("TURNOVER_COUNT between", value1, value2, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andTurnoverCountNotBetween(Double value1, Double value2) {
            addCriterion("TURNOVER_COUNT not between", value1, value2, "turnoverCount");
            return (Criteria) this;
        }

        public Criteria andDateTimeIsNull() {
            addCriterion("DATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDateTimeIsNotNull() {
            addCriterion("DATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDateTimeEqualTo(Date value) {
            addCriterion("DATE_TIME =", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeNotEqualTo(Date value) {
            addCriterion("DATE_TIME <>", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeGreaterThan(Date value) {
            addCriterion("DATE_TIME >", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_TIME >=", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeLessThan(Date value) {
            addCriterion("DATE_TIME <", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("DATE_TIME <=", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeIn(List<Date> values) {
            addCriterion("DATE_TIME in", values, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeNotIn(List<Date> values) {
            addCriterion("DATE_TIME not in", values, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeBetween(Date value1, Date value2) {
            addCriterion("DATE_TIME between", value1, value2, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("DATE_TIME not between", value1, value2, "dateTime");
            return (Criteria) this;
        }

        public Criteria andFundStatusIsNull() {
            addCriterion("FUND_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andFundStatusIsNotNull() {
            addCriterion("FUND_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andFundStatusEqualTo(String value) {
            addCriterion("FUND_STATUS =", value, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusNotEqualTo(String value) {
            addCriterion("FUND_STATUS <>", value, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusGreaterThan(String value) {
            addCriterion("FUND_STATUS >", value, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusGreaterThanOrEqualTo(String value) {
            addCriterion("FUND_STATUS >=", value, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusLessThan(String value) {
            addCriterion("FUND_STATUS <", value, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusLessThanOrEqualTo(String value) {
            addCriterion("FUND_STATUS <=", value, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusLike(String value) {
            addCriterion("FUND_STATUS like", value, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusNotLike(String value) {
            addCriterion("FUND_STATUS not like", value, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusIn(List<String> values) {
            addCriterion("FUND_STATUS in", values, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusNotIn(List<String> values) {
            addCriterion("FUND_STATUS not in", values, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusBetween(String value1, String value2) {
            addCriterion("FUND_STATUS between", value1, value2, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andFundStatusNotBetween(String value1, String value2) {
            addCriterion("FUND_STATUS not between", value1, value2, "fundStatus");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("UPDATED_TIME =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("UPDATED_TIME <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("UPDATED_TIME >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_TIME >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("UPDATED_TIME <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_TIME <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("UPDATED_TIME in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("UPDATED_TIME not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATED_TIME between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_TIME not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNull() {
            addCriterion("RESERVED1 is null");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNotNull() {
            addCriterion("RESERVED1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved1EqualTo(String value) {
            addCriterion("RESERVED1 =", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotEqualTo(String value) {
            addCriterion("RESERVED1 <>", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThan(String value) {
            addCriterion("RESERVED1 >", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVED1 >=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThan(String value) {
            addCriterion("RESERVED1 <", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThanOrEqualTo(String value) {
            addCriterion("RESERVED1 <=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Like(String value) {
            addCriterion("RESERVED1 like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotLike(String value) {
            addCriterion("RESERVED1 not like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1In(List<String> values) {
            addCriterion("RESERVED1 in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotIn(List<String> values) {
            addCriterion("RESERVED1 not in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Between(String value1, String value2) {
            addCriterion("RESERVED1 between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotBetween(String value1, String value2) {
            addCriterion("RESERVED1 not between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNull() {
            addCriterion("RESERVED2 is null");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNotNull() {
            addCriterion("RESERVED2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved2EqualTo(String value) {
            addCriterion("RESERVED2 =", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotEqualTo(String value) {
            addCriterion("RESERVED2 <>", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThan(String value) {
            addCriterion("RESERVED2 >", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVED2 >=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThan(String value) {
            addCriterion("RESERVED2 <", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThanOrEqualTo(String value) {
            addCriterion("RESERVED2 <=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Like(String value) {
            addCriterion("RESERVED2 like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotLike(String value) {
            addCriterion("RESERVED2 not like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2In(List<String> values) {
            addCriterion("RESERVED2 in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotIn(List<String> values) {
            addCriterion("RESERVED2 not in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Between(String value1, String value2) {
            addCriterion("RESERVED2 between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotBetween(String value1, String value2) {
            addCriterion("RESERVED2 not between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andFundIdLikeInsensitive(String value) {
            addCriterion("upper(FUND_ID) like", value.toUpperCase(), "fundId");
            return (Criteria) this;
        }

        public Criteria andUserIdLikeInsensitive(String value) {
            addCriterion("upper(USER_ID) like", value.toUpperCase(), "userId");
            return (Criteria) this;
        }

        public Criteria andDmtCnameLikeInsensitive(String value) {
            addCriterion("upper(DMT_CNAME) like", value.toUpperCase(), "dmtCname");
            return (Criteria) this;
        }

        public Criteria andDmtEnameLikeInsensitive(String value) {
            addCriterion("upper(DMT_ENAME) like", value.toUpperCase(), "dmtEname");
            return (Criteria) this;
        }

        public Criteria andGenisAddrLikeInsensitive(String value) {
            addCriterion("upper(GENIS_ADDR) like", value.toUpperCase(), "genisAddr");
            return (Criteria) this;
        }

        public Criteria andGenisOrgIdLikeInsensitive(String value) {
            addCriterion("upper(GENIS_ORG_ID) like", value.toUpperCase(), "genisOrgId");
            return (Criteria) this;
        }

        public Criteria andFundStatusLikeInsensitive(String value) {
            addCriterion("upper(FUND_STATUS) like", value.toUpperCase(), "fundStatus");
            return (Criteria) this;
        }

        public Criteria andReserved1LikeInsensitive(String value) {
            addCriterion("upper(RESERVED1) like", value.toUpperCase(), "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2LikeInsensitive(String value) {
            addCriterion("upper(RESERVED2) like", value.toUpperCase(), "reserved2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_FUND
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 01 14:31:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}