package org.fc.wlt.ordbgens.wlt.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="WLT_PEND")
@AllArgsConstructor
@NoArgsConstructor
public class WLTPend extends WLTPendKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.BS_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String bsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.SOURCE_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String sourceAssetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.SOURCE_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Double sourceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.TARGET_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String targetFundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.TARGET_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Double targetAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.PEND_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String pendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.AUTO_COMMIT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String autoCommit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.TOTAL_FEE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Double totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.PEND_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String pendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_PEND.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.BS_CODE
     *
     * @return the value of WLT_PEND.BS_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getBsCode() {
        return bsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.BS_CODE
     *
     * @param bsCode the value for WLT_PEND.BS_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setBsCode(String bsCode) {
        this.bsCode = bsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.USER_ID
     *
     * @return the value of WLT_PEND.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.USER_ID
     *
     * @param userId the value for WLT_PEND.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.SOURCE_ASSET_ID
     *
     * @return the value of WLT_PEND.SOURCE_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getSourceAssetId() {
        return sourceAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.SOURCE_ASSET_ID
     *
     * @param sourceAssetId the value for WLT_PEND.SOURCE_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setSourceAssetId(String sourceAssetId) {
        this.sourceAssetId = sourceAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.SOURCE_AMOUNT
     *
     * @return the value of WLT_PEND.SOURCE_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Double getSourceAmount() {
        return sourceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.SOURCE_AMOUNT
     *
     * @param sourceAmount the value for WLT_PEND.SOURCE_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setSourceAmount(Double sourceAmount) {
        this.sourceAmount = sourceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.TARGET_FUND_ID
     *
     * @return the value of WLT_PEND.TARGET_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getTargetFundId() {
        return targetFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.TARGET_FUND_ID
     *
     * @param targetFundId the value for WLT_PEND.TARGET_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setTargetFundId(String targetFundId) {
        this.targetFundId = targetFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.TARGET_AMOUNT
     *
     * @return the value of WLT_PEND.TARGET_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Double getTargetAmount() {
        return targetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.TARGET_AMOUNT
     *
     * @param targetAmount the value for WLT_PEND.TARGET_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setTargetAmount(Double targetAmount) {
        this.targetAmount = targetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.PEND_TYPE
     *
     * @return the value of WLT_PEND.PEND_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getPendType() {
        return pendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.PEND_TYPE
     *
     * @param pendType the value for WLT_PEND.PEND_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setPendType(String pendType) {
        this.pendType = pendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.AUTO_COMMIT
     *
     * @return the value of WLT_PEND.AUTO_COMMIT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getAutoCommit() {
        return autoCommit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.AUTO_COMMIT
     *
     * @param autoCommit the value for WLT_PEND.AUTO_COMMIT
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setAutoCommit(String autoCommit) {
        this.autoCommit = autoCommit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.TOTAL_FEE
     *
     * @return the value of WLT_PEND.TOTAL_FEE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.TOTAL_FEE
     *
     * @param totalFee the value for WLT_PEND.TOTAL_FEE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.PEND_STATUS
     *
     * @return the value of WLT_PEND.PEND_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getPendStatus() {
        return pendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.PEND_STATUS
     *
     * @param pendStatus the value for WLT_PEND.PEND_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setPendStatus(String pendStatus) {
        this.pendStatus = pendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.CREATED_TIME
     *
     * @return the value of WLT_PEND.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.CREATED_TIME
     *
     * @param createdTime the value for WLT_PEND.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.UPDATED_TIME
     *
     * @return the value of WLT_PEND.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.UPDATED_TIME
     *
     * @param updatedTime the value for WLT_PEND.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.RESERVED1
     *
     * @return the value of WLT_PEND.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.RESERVED1
     *
     * @param reserved1 the value for WLT_PEND.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_PEND.RESERVED2
     *
     * @return the value of WLT_PEND.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_PEND.RESERVED2
     *
     * @param reserved2 the value for WLT_PEND.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_PEND
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTPend other = (WLTPend) that;
        return (this.getPendId() == null ? other.getPendId() == null : this.getPendId().equals(other.getPendId()))
            && (this.getBsCode() == null ? other.getBsCode() == null : this.getBsCode().equals(other.getBsCode()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSourceAssetId() == null ? other.getSourceAssetId() == null : this.getSourceAssetId().equals(other.getSourceAssetId()))
            && (this.getSourceAmount() == null ? other.getSourceAmount() == null : this.getSourceAmount().equals(other.getSourceAmount()))
            && (this.getTargetFundId() == null ? other.getTargetFundId() == null : this.getTargetFundId().equals(other.getTargetFundId()))
            && (this.getTargetAmount() == null ? other.getTargetAmount() == null : this.getTargetAmount().equals(other.getTargetAmount()))
            && (this.getPendType() == null ? other.getPendType() == null : this.getPendType().equals(other.getPendType()))
            && (this.getAutoCommit() == null ? other.getAutoCommit() == null : this.getAutoCommit().equals(other.getAutoCommit()))
            && (this.getTotalFee() == null ? other.getTotalFee() == null : this.getTotalFee().equals(other.getTotalFee()))
            && (this.getPendStatus() == null ? other.getPendStatus() == null : this.getPendStatus().equals(other.getPendStatus()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()))
            && (this.getReserved1() == null ? other.getReserved1() == null : this.getReserved1().equals(other.getReserved1()))
            && (this.getReserved2() == null ? other.getReserved2() == null : this.getReserved2().equals(other.getReserved2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_PEND
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPendId() == null) ? 0 : getPendId().hashCode());
        result = prime * result + ((getBsCode() == null) ? 0 : getBsCode().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSourceAssetId() == null) ? 0 : getSourceAssetId().hashCode());
        result = prime * result + ((getSourceAmount() == null) ? 0 : getSourceAmount().hashCode());
        result = prime * result + ((getTargetFundId() == null) ? 0 : getTargetFundId().hashCode());
        result = prime * result + ((getTargetAmount() == null) ? 0 : getTargetAmount().hashCode());
        result = prime * result + ((getPendType() == null) ? 0 : getPendType().hashCode());
        result = prime * result + ((getAutoCommit() == null) ? 0 : getAutoCommit().hashCode());
        result = prime * result + ((getTotalFee() == null) ? 0 : getTotalFee().hashCode());
        result = prime * result + ((getPendStatus() == null) ? 0 : getPendStatus().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        result = prime * result + ((getReserved1() == null) ? 0 : getReserved1().hashCode());
        result = prime * result + ((getReserved2() == null) ? 0 : getReserved2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_PEND
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bsCode=").append(bsCode);
        sb.append(", userId=").append(userId);
        sb.append(", sourceAssetId=").append(sourceAssetId);
        sb.append(", sourceAmount=").append(sourceAmount);
        sb.append(", targetFundId=").append(targetFundId);
        sb.append(", targetAmount=").append(targetAmount);
        sb.append(", pendType=").append(pendType);
        sb.append(", autoCommit=").append(autoCommit);
        sb.append(", totalFee=").append(totalFee);
        sb.append(", pendStatus=").append(pendStatus);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", reserved1=").append(reserved1);
        sb.append(", reserved2=").append(reserved2);
        sb.append("]");
        return sb.toString();
    }
}