package org.fc.wlt.ordbgens.wlt.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="WLT_TRANSFER")
@AllArgsConstructor
@NoArgsConstructor
public class WLTTransfer extends WLTTransferKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.SOURCE_USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String sourceUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.SOURCE_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String sourceAssetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.SOURCE_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private Double sourceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.SOURCE_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String sourceFundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.TARGET_USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String targetUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.TARGET_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String targetAssetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.TARGET_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private Double targetAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.TARGET_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String targetFundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.TOTAL_FEE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private Double totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.TRANSFER_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String transferType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.PEND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String pendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.TRANSFER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String transferStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.RESERVED_01
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String reserved01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_TRANSFER.RESERVED_02
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String reserved02;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.SOURCE_USER_ID
     *
     * @return the value of WLT_TRANSFER.SOURCE_USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getSourceUserId() {
        return sourceUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.SOURCE_USER_ID
     *
     * @param sourceUserId the value for WLT_TRANSFER.SOURCE_USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setSourceUserId(String sourceUserId) {
        this.sourceUserId = sourceUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.SOURCE_ASSET_ID
     *
     * @return the value of WLT_TRANSFER.SOURCE_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getSourceAssetId() {
        return sourceAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.SOURCE_ASSET_ID
     *
     * @param sourceAssetId the value for WLT_TRANSFER.SOURCE_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setSourceAssetId(String sourceAssetId) {
        this.sourceAssetId = sourceAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.SOURCE_AMOUNT
     *
     * @return the value of WLT_TRANSFER.SOURCE_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Double getSourceAmount() {
        return sourceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.SOURCE_AMOUNT
     *
     * @param sourceAmount the value for WLT_TRANSFER.SOURCE_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setSourceAmount(Double sourceAmount) {
        this.sourceAmount = sourceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.SOURCE_FUND_ID
     *
     * @return the value of WLT_TRANSFER.SOURCE_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getSourceFundId() {
        return sourceFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.SOURCE_FUND_ID
     *
     * @param sourceFundId the value for WLT_TRANSFER.SOURCE_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setSourceFundId(String sourceFundId) {
        this.sourceFundId = sourceFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.TARGET_USER_ID
     *
     * @return the value of WLT_TRANSFER.TARGET_USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getTargetUserId() {
        return targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.TARGET_USER_ID
     *
     * @param targetUserId the value for WLT_TRANSFER.TARGET_USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setTargetUserId(String targetUserId) {
        this.targetUserId = targetUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.TARGET_ASSET_ID
     *
     * @return the value of WLT_TRANSFER.TARGET_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getTargetAssetId() {
        return targetAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.TARGET_ASSET_ID
     *
     * @param targetAssetId the value for WLT_TRANSFER.TARGET_ASSET_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setTargetAssetId(String targetAssetId) {
        this.targetAssetId = targetAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.TARGET_AMOUNT
     *
     * @return the value of WLT_TRANSFER.TARGET_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Double getTargetAmount() {
        return targetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.TARGET_AMOUNT
     *
     * @param targetAmount the value for WLT_TRANSFER.TARGET_AMOUNT
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setTargetAmount(Double targetAmount) {
        this.targetAmount = targetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.TARGET_FUND_ID
     *
     * @return the value of WLT_TRANSFER.TARGET_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getTargetFundId() {
        return targetFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.TARGET_FUND_ID
     *
     * @param targetFundId the value for WLT_TRANSFER.TARGET_FUND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setTargetFundId(String targetFundId) {
        this.targetFundId = targetFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.TOTAL_FEE
     *
     * @return the value of WLT_TRANSFER.TOTAL_FEE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.TOTAL_FEE
     *
     * @param totalFee the value for WLT_TRANSFER.TOTAL_FEE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.TRANSFER_TYPE
     *
     * @return the value of WLT_TRANSFER.TRANSFER_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getTransferType() {
        return transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.TRANSFER_TYPE
     *
     * @param transferType the value for WLT_TRANSFER.TRANSFER_TYPE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setTransferType(String transferType) {
        this.transferType = transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.PEND_ID
     *
     * @return the value of WLT_TRANSFER.PEND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getPendId() {
        return pendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.PEND_ID
     *
     * @param pendId the value for WLT_TRANSFER.PEND_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setPendId(String pendId) {
        this.pendId = pendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.TRANSFER_STATUS
     *
     * @return the value of WLT_TRANSFER.TRANSFER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getTransferStatus() {
        return transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.TRANSFER_STATUS
     *
     * @param transferStatus the value for WLT_TRANSFER.TRANSFER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setTransferStatus(String transferStatus) {
        this.transferStatus = transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.CREATED_TIME
     *
     * @return the value of WLT_TRANSFER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.CREATED_TIME
     *
     * @param createdTime the value for WLT_TRANSFER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.UPDATED_TIME
     *
     * @return the value of WLT_TRANSFER.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.UPDATED_TIME
     *
     * @param updatedTime the value for WLT_TRANSFER.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.RESERVED_01
     *
     * @return the value of WLT_TRANSFER.RESERVED_01
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getReserved01() {
        return reserved01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.RESERVED_01
     *
     * @param reserved01 the value for WLT_TRANSFER.RESERVED_01
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setReserved01(String reserved01) {
        this.reserved01 = reserved01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_TRANSFER.RESERVED_02
     *
     * @return the value of WLT_TRANSFER.RESERVED_02
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getReserved02() {
        return reserved02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_TRANSFER.RESERVED_02
     *
     * @param reserved02 the value for WLT_TRANSFER.RESERVED_02
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setReserved02(String reserved02) {
        this.reserved02 = reserved02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTTransfer other = (WLTTransfer) that;
        return (this.getTransferId() == null ? other.getTransferId() == null : this.getTransferId().equals(other.getTransferId()))
            && (this.getSourceUserId() == null ? other.getSourceUserId() == null : this.getSourceUserId().equals(other.getSourceUserId()))
            && (this.getSourceAssetId() == null ? other.getSourceAssetId() == null : this.getSourceAssetId().equals(other.getSourceAssetId()))
            && (this.getSourceAmount() == null ? other.getSourceAmount() == null : this.getSourceAmount().equals(other.getSourceAmount()))
            && (this.getSourceFundId() == null ? other.getSourceFundId() == null : this.getSourceFundId().equals(other.getSourceFundId()))
            && (this.getTargetUserId() == null ? other.getTargetUserId() == null : this.getTargetUserId().equals(other.getTargetUserId()))
            && (this.getTargetAssetId() == null ? other.getTargetAssetId() == null : this.getTargetAssetId().equals(other.getTargetAssetId()))
            && (this.getTargetAmount() == null ? other.getTargetAmount() == null : this.getTargetAmount().equals(other.getTargetAmount()))
            && (this.getTargetFundId() == null ? other.getTargetFundId() == null : this.getTargetFundId().equals(other.getTargetFundId()))
            && (this.getTotalFee() == null ? other.getTotalFee() == null : this.getTotalFee().equals(other.getTotalFee()))
            && (this.getTransferType() == null ? other.getTransferType() == null : this.getTransferType().equals(other.getTransferType()))
            && (this.getPendId() == null ? other.getPendId() == null : this.getPendId().equals(other.getPendId()))
            && (this.getTransferStatus() == null ? other.getTransferStatus() == null : this.getTransferStatus().equals(other.getTransferStatus()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()))
            && (this.getReserved01() == null ? other.getReserved01() == null : this.getReserved01().equals(other.getReserved01()))
            && (this.getReserved02() == null ? other.getReserved02() == null : this.getReserved02().equals(other.getReserved02()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTransferId() == null) ? 0 : getTransferId().hashCode());
        result = prime * result + ((getSourceUserId() == null) ? 0 : getSourceUserId().hashCode());
        result = prime * result + ((getSourceAssetId() == null) ? 0 : getSourceAssetId().hashCode());
        result = prime * result + ((getSourceAmount() == null) ? 0 : getSourceAmount().hashCode());
        result = prime * result + ((getSourceFundId() == null) ? 0 : getSourceFundId().hashCode());
        result = prime * result + ((getTargetUserId() == null) ? 0 : getTargetUserId().hashCode());
        result = prime * result + ((getTargetAssetId() == null) ? 0 : getTargetAssetId().hashCode());
        result = prime * result + ((getTargetAmount() == null) ? 0 : getTargetAmount().hashCode());
        result = prime * result + ((getTargetFundId() == null) ? 0 : getTargetFundId().hashCode());
        result = prime * result + ((getTotalFee() == null) ? 0 : getTotalFee().hashCode());
        result = prime * result + ((getTransferType() == null) ? 0 : getTransferType().hashCode());
        result = prime * result + ((getPendId() == null) ? 0 : getPendId().hashCode());
        result = prime * result + ((getTransferStatus() == null) ? 0 : getTransferStatus().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        result = prime * result + ((getReserved01() == null) ? 0 : getReserved01().hashCode());
        result = prime * result + ((getReserved02() == null) ? 0 : getReserved02().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sourceUserId=").append(sourceUserId);
        sb.append(", sourceAssetId=").append(sourceAssetId);
        sb.append(", sourceAmount=").append(sourceAmount);
        sb.append(", sourceFundId=").append(sourceFundId);
        sb.append(", targetUserId=").append(targetUserId);
        sb.append(", targetAssetId=").append(targetAssetId);
        sb.append(", targetAmount=").append(targetAmount);
        sb.append(", targetFundId=").append(targetFundId);
        sb.append(", totalFee=").append(totalFee);
        sb.append(", transferType=").append(transferType);
        sb.append(", pendId=").append(pendId);
        sb.append(", transferStatus=").append(transferStatus);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", reserved01=").append(reserved01);
        sb.append(", reserved02=").append(reserved02);
        sb.append("]");
        return sb.toString();
    }
}