package org.fc.wlt.ordbgens.wlt.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class WLTTransferExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected boolean forUpdate;

    protected String groupByClause;

    String selectCols;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public WLTTransferExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
        this.forUpdate=false;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setForUpdate(boolean forUpdate) {
         this.forUpdate = forUpdate;
    }

    public boolean isForUpdate() {
          return forUpdate;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransferIdIsNull() {
            addCriterion("TRANSFER_ID is null");
            return (Criteria) this;
        }

        public Criteria andTransferIdIsNotNull() {
            addCriterion("TRANSFER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTransferIdEqualTo(String value) {
            addCriterion("TRANSFER_ID =", value, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdNotEqualTo(String value) {
            addCriterion("TRANSFER_ID <>", value, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdGreaterThan(String value) {
            addCriterion("TRANSFER_ID >", value, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFER_ID >=", value, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdLessThan(String value) {
            addCriterion("TRANSFER_ID <", value, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdLessThanOrEqualTo(String value) {
            addCriterion("TRANSFER_ID <=", value, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdLike(String value) {
            addCriterion("TRANSFER_ID like", value, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdNotLike(String value) {
            addCriterion("TRANSFER_ID not like", value, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdIn(List<String> values) {
            addCriterion("TRANSFER_ID in", values, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdNotIn(List<String> values) {
            addCriterion("TRANSFER_ID not in", values, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdBetween(String value1, String value2) {
            addCriterion("TRANSFER_ID between", value1, value2, "transferId");
            return (Criteria) this;
        }

        public Criteria andTransferIdNotBetween(String value1, String value2) {
            addCriterion("TRANSFER_ID not between", value1, value2, "transferId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdIsNull() {
            addCriterion("SOURCE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdIsNotNull() {
            addCriterion("SOURCE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdEqualTo(String value) {
            addCriterion("SOURCE_USER_ID =", value, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdNotEqualTo(String value) {
            addCriterion("SOURCE_USER_ID <>", value, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdGreaterThan(String value) {
            addCriterion("SOURCE_USER_ID >", value, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_USER_ID >=", value, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdLessThan(String value) {
            addCriterion("SOURCE_USER_ID <", value, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_USER_ID <=", value, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdLike(String value) {
            addCriterion("SOURCE_USER_ID like", value, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdNotLike(String value) {
            addCriterion("SOURCE_USER_ID not like", value, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdIn(List<String> values) {
            addCriterion("SOURCE_USER_ID in", values, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdNotIn(List<String> values) {
            addCriterion("SOURCE_USER_ID not in", values, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdBetween(String value1, String value2) {
            addCriterion("SOURCE_USER_ID between", value1, value2, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdNotBetween(String value1, String value2) {
            addCriterion("SOURCE_USER_ID not between", value1, value2, "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdIsNull() {
            addCriterion("SOURCE_ASSET_ID is null");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdIsNotNull() {
            addCriterion("SOURCE_ASSET_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdEqualTo(String value) {
            addCriterion("SOURCE_ASSET_ID =", value, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdNotEqualTo(String value) {
            addCriterion("SOURCE_ASSET_ID <>", value, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdGreaterThan(String value) {
            addCriterion("SOURCE_ASSET_ID >", value, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_ASSET_ID >=", value, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdLessThan(String value) {
            addCriterion("SOURCE_ASSET_ID <", value, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_ASSET_ID <=", value, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdLike(String value) {
            addCriterion("SOURCE_ASSET_ID like", value, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdNotLike(String value) {
            addCriterion("SOURCE_ASSET_ID not like", value, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdIn(List<String> values) {
            addCriterion("SOURCE_ASSET_ID in", values, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdNotIn(List<String> values) {
            addCriterion("SOURCE_ASSET_ID not in", values, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdBetween(String value1, String value2) {
            addCriterion("SOURCE_ASSET_ID between", value1, value2, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdNotBetween(String value1, String value2) {
            addCriterion("SOURCE_ASSET_ID not between", value1, value2, "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceAmountIsNull() {
            addCriterion("SOURCE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andSourceAmountIsNotNull() {
            addCriterion("SOURCE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSourceAmountEqualTo(Double value) {
            addCriterion("SOURCE_AMOUNT =", value, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountNotEqualTo(Double value) {
            addCriterion("SOURCE_AMOUNT <>", value, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountGreaterThan(Double value) {
            addCriterion("SOURCE_AMOUNT >", value, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("SOURCE_AMOUNT >=", value, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountLessThan(Double value) {
            addCriterion("SOURCE_AMOUNT <", value, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountLessThanOrEqualTo(Double value) {
            addCriterion("SOURCE_AMOUNT <=", value, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountIn(List<Double> values) {
            addCriterion("SOURCE_AMOUNT in", values, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountNotIn(List<Double> values) {
            addCriterion("SOURCE_AMOUNT not in", values, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountBetween(Double value1, Double value2) {
            addCriterion("SOURCE_AMOUNT between", value1, value2, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceAmountNotBetween(Double value1, Double value2) {
            addCriterion("SOURCE_AMOUNT not between", value1, value2, "sourceAmount");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdIsNull() {
            addCriterion("SOURCE_FUND_ID is null");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdIsNotNull() {
            addCriterion("SOURCE_FUND_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdEqualTo(String value) {
            addCriterion("SOURCE_FUND_ID =", value, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdNotEqualTo(String value) {
            addCriterion("SOURCE_FUND_ID <>", value, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdGreaterThan(String value) {
            addCriterion("SOURCE_FUND_ID >", value, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_FUND_ID >=", value, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdLessThan(String value) {
            addCriterion("SOURCE_FUND_ID <", value, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_FUND_ID <=", value, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdLike(String value) {
            addCriterion("SOURCE_FUND_ID like", value, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdNotLike(String value) {
            addCriterion("SOURCE_FUND_ID not like", value, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdIn(List<String> values) {
            addCriterion("SOURCE_FUND_ID in", values, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdNotIn(List<String> values) {
            addCriterion("SOURCE_FUND_ID not in", values, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdBetween(String value1, String value2) {
            addCriterion("SOURCE_FUND_ID between", value1, value2, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdNotBetween(String value1, String value2) {
            addCriterion("SOURCE_FUND_ID not between", value1, value2, "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdIsNull() {
            addCriterion("TARGET_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdIsNotNull() {
            addCriterion("TARGET_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdEqualTo(String value) {
            addCriterion("TARGET_USER_ID =", value, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdNotEqualTo(String value) {
            addCriterion("TARGET_USER_ID <>", value, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdGreaterThan(String value) {
            addCriterion("TARGET_USER_ID >", value, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("TARGET_USER_ID >=", value, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdLessThan(String value) {
            addCriterion("TARGET_USER_ID <", value, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdLessThanOrEqualTo(String value) {
            addCriterion("TARGET_USER_ID <=", value, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdLike(String value) {
            addCriterion("TARGET_USER_ID like", value, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdNotLike(String value) {
            addCriterion("TARGET_USER_ID not like", value, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdIn(List<String> values) {
            addCriterion("TARGET_USER_ID in", values, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdNotIn(List<String> values) {
            addCriterion("TARGET_USER_ID not in", values, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdBetween(String value1, String value2) {
            addCriterion("TARGET_USER_ID between", value1, value2, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdNotBetween(String value1, String value2) {
            addCriterion("TARGET_USER_ID not between", value1, value2, "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdIsNull() {
            addCriterion("TARGET_ASSET_ID is null");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdIsNotNull() {
            addCriterion("TARGET_ASSET_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdEqualTo(String value) {
            addCriterion("TARGET_ASSET_ID =", value, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdNotEqualTo(String value) {
            addCriterion("TARGET_ASSET_ID <>", value, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdGreaterThan(String value) {
            addCriterion("TARGET_ASSET_ID >", value, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdGreaterThanOrEqualTo(String value) {
            addCriterion("TARGET_ASSET_ID >=", value, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdLessThan(String value) {
            addCriterion("TARGET_ASSET_ID <", value, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdLessThanOrEqualTo(String value) {
            addCriterion("TARGET_ASSET_ID <=", value, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdLike(String value) {
            addCriterion("TARGET_ASSET_ID like", value, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdNotLike(String value) {
            addCriterion("TARGET_ASSET_ID not like", value, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdIn(List<String> values) {
            addCriterion("TARGET_ASSET_ID in", values, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdNotIn(List<String> values) {
            addCriterion("TARGET_ASSET_ID not in", values, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdBetween(String value1, String value2) {
            addCriterion("TARGET_ASSET_ID between", value1, value2, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdNotBetween(String value1, String value2) {
            addCriterion("TARGET_ASSET_ID not between", value1, value2, "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetAmountIsNull() {
            addCriterion("TARGET_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTargetAmountIsNotNull() {
            addCriterion("TARGET_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTargetAmountEqualTo(Double value) {
            addCriterion("TARGET_AMOUNT =", value, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountNotEqualTo(Double value) {
            addCriterion("TARGET_AMOUNT <>", value, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountGreaterThan(Double value) {
            addCriterion("TARGET_AMOUNT >", value, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("TARGET_AMOUNT >=", value, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountLessThan(Double value) {
            addCriterion("TARGET_AMOUNT <", value, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountLessThanOrEqualTo(Double value) {
            addCriterion("TARGET_AMOUNT <=", value, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountIn(List<Double> values) {
            addCriterion("TARGET_AMOUNT in", values, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountNotIn(List<Double> values) {
            addCriterion("TARGET_AMOUNT not in", values, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountBetween(Double value1, Double value2) {
            addCriterion("TARGET_AMOUNT between", value1, value2, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetAmountNotBetween(Double value1, Double value2) {
            addCriterion("TARGET_AMOUNT not between", value1, value2, "targetAmount");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdIsNull() {
            addCriterion("TARGET_FUND_ID is null");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdIsNotNull() {
            addCriterion("TARGET_FUND_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdEqualTo(String value) {
            addCriterion("TARGET_FUND_ID =", value, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdNotEqualTo(String value) {
            addCriterion("TARGET_FUND_ID <>", value, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdGreaterThan(String value) {
            addCriterion("TARGET_FUND_ID >", value, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdGreaterThanOrEqualTo(String value) {
            addCriterion("TARGET_FUND_ID >=", value, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdLessThan(String value) {
            addCriterion("TARGET_FUND_ID <", value, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdLessThanOrEqualTo(String value) {
            addCriterion("TARGET_FUND_ID <=", value, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdLike(String value) {
            addCriterion("TARGET_FUND_ID like", value, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdNotLike(String value) {
            addCriterion("TARGET_FUND_ID not like", value, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdIn(List<String> values) {
            addCriterion("TARGET_FUND_ID in", values, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdNotIn(List<String> values) {
            addCriterion("TARGET_FUND_ID not in", values, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdBetween(String value1, String value2) {
            addCriterion("TARGET_FUND_ID between", value1, value2, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdNotBetween(String value1, String value2) {
            addCriterion("TARGET_FUND_ID not between", value1, value2, "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNull() {
            addCriterion("TOTAL_FEE is null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNotNull() {
            addCriterion("TOTAL_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeEqualTo(Double value) {
            addCriterion("TOTAL_FEE =", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotEqualTo(Double value) {
            addCriterion("TOTAL_FEE <>", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThan(Double value) {
            addCriterion("TOTAL_FEE >", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("TOTAL_FEE >=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThan(Double value) {
            addCriterion("TOTAL_FEE <", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThanOrEqualTo(Double value) {
            addCriterion("TOTAL_FEE <=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIn(List<Double> values) {
            addCriterion("TOTAL_FEE in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotIn(List<Double> values) {
            addCriterion("TOTAL_FEE not in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeBetween(Double value1, Double value2) {
            addCriterion("TOTAL_FEE between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotBetween(Double value1, Double value2) {
            addCriterion("TOTAL_FEE not between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTransferTypeIsNull() {
            addCriterion("TRANSFER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTransferTypeIsNotNull() {
            addCriterion("TRANSFER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTransferTypeEqualTo(String value) {
            addCriterion("TRANSFER_TYPE =", value, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeNotEqualTo(String value) {
            addCriterion("TRANSFER_TYPE <>", value, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeGreaterThan(String value) {
            addCriterion("TRANSFER_TYPE >", value, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFER_TYPE >=", value, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeLessThan(String value) {
            addCriterion("TRANSFER_TYPE <", value, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeLessThanOrEqualTo(String value) {
            addCriterion("TRANSFER_TYPE <=", value, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeLike(String value) {
            addCriterion("TRANSFER_TYPE like", value, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeNotLike(String value) {
            addCriterion("TRANSFER_TYPE not like", value, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeIn(List<String> values) {
            addCriterion("TRANSFER_TYPE in", values, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeNotIn(List<String> values) {
            addCriterion("TRANSFER_TYPE not in", values, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeBetween(String value1, String value2) {
            addCriterion("TRANSFER_TYPE between", value1, value2, "transferType");
            return (Criteria) this;
        }

        public Criteria andTransferTypeNotBetween(String value1, String value2) {
            addCriterion("TRANSFER_TYPE not between", value1, value2, "transferType");
            return (Criteria) this;
        }

        public Criteria andPendIdIsNull() {
            addCriterion("PEND_ID is null");
            return (Criteria) this;
        }

        public Criteria andPendIdIsNotNull() {
            addCriterion("PEND_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPendIdEqualTo(String value) {
            addCriterion("PEND_ID =", value, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdNotEqualTo(String value) {
            addCriterion("PEND_ID <>", value, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdGreaterThan(String value) {
            addCriterion("PEND_ID >", value, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdGreaterThanOrEqualTo(String value) {
            addCriterion("PEND_ID >=", value, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdLessThan(String value) {
            addCriterion("PEND_ID <", value, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdLessThanOrEqualTo(String value) {
            addCriterion("PEND_ID <=", value, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdLike(String value) {
            addCriterion("PEND_ID like", value, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdNotLike(String value) {
            addCriterion("PEND_ID not like", value, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdIn(List<String> values) {
            addCriterion("PEND_ID in", values, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdNotIn(List<String> values) {
            addCriterion("PEND_ID not in", values, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdBetween(String value1, String value2) {
            addCriterion("PEND_ID between", value1, value2, "pendId");
            return (Criteria) this;
        }

        public Criteria andPendIdNotBetween(String value1, String value2) {
            addCriterion("PEND_ID not between", value1, value2, "pendId");
            return (Criteria) this;
        }

        public Criteria andTransferStatusIsNull() {
            addCriterion("TRANSFER_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andTransferStatusIsNotNull() {
            addCriterion("TRANSFER_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andTransferStatusEqualTo(String value) {
            addCriterion("TRANSFER_STATUS =", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusNotEqualTo(String value) {
            addCriterion("TRANSFER_STATUS <>", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusGreaterThan(String value) {
            addCriterion("TRANSFER_STATUS >", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSFER_STATUS >=", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusLessThan(String value) {
            addCriterion("TRANSFER_STATUS <", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusLessThanOrEqualTo(String value) {
            addCriterion("TRANSFER_STATUS <=", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusLike(String value) {
            addCriterion("TRANSFER_STATUS like", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusNotLike(String value) {
            addCriterion("TRANSFER_STATUS not like", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusIn(List<String> values) {
            addCriterion("TRANSFER_STATUS in", values, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusNotIn(List<String> values) {
            addCriterion("TRANSFER_STATUS not in", values, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusBetween(String value1, String value2) {
            addCriterion("TRANSFER_STATUS between", value1, value2, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusNotBetween(String value1, String value2) {
            addCriterion("TRANSFER_STATUS not between", value1, value2, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("UPDATED_TIME =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("UPDATED_TIME <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("UPDATED_TIME >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_TIME >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("UPDATED_TIME <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_TIME <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("UPDATED_TIME in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("UPDATED_TIME not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATED_TIME between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_TIME not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andReserved01IsNull() {
            addCriterion("RESERVED_01 is null");
            return (Criteria) this;
        }

        public Criteria andReserved01IsNotNull() {
            addCriterion("RESERVED_01 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved01EqualTo(String value) {
            addCriterion("RESERVED_01 =", value, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01NotEqualTo(String value) {
            addCriterion("RESERVED_01 <>", value, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01GreaterThan(String value) {
            addCriterion("RESERVED_01 >", value, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVED_01 >=", value, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01LessThan(String value) {
            addCriterion("RESERVED_01 <", value, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01LessThanOrEqualTo(String value) {
            addCriterion("RESERVED_01 <=", value, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01Like(String value) {
            addCriterion("RESERVED_01 like", value, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01NotLike(String value) {
            addCriterion("RESERVED_01 not like", value, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01In(List<String> values) {
            addCriterion("RESERVED_01 in", values, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01NotIn(List<String> values) {
            addCriterion("RESERVED_01 not in", values, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01Between(String value1, String value2) {
            addCriterion("RESERVED_01 between", value1, value2, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved01NotBetween(String value1, String value2) {
            addCriterion("RESERVED_01 not between", value1, value2, "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved02IsNull() {
            addCriterion("RESERVED_02 is null");
            return (Criteria) this;
        }

        public Criteria andReserved02IsNotNull() {
            addCriterion("RESERVED_02 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved02EqualTo(String value) {
            addCriterion("RESERVED_02 =", value, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02NotEqualTo(String value) {
            addCriterion("RESERVED_02 <>", value, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02GreaterThan(String value) {
            addCriterion("RESERVED_02 >", value, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVED_02 >=", value, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02LessThan(String value) {
            addCriterion("RESERVED_02 <", value, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02LessThanOrEqualTo(String value) {
            addCriterion("RESERVED_02 <=", value, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02Like(String value) {
            addCriterion("RESERVED_02 like", value, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02NotLike(String value) {
            addCriterion("RESERVED_02 not like", value, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02In(List<String> values) {
            addCriterion("RESERVED_02 in", values, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02NotIn(List<String> values) {
            addCriterion("RESERVED_02 not in", values, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02Between(String value1, String value2) {
            addCriterion("RESERVED_02 between", value1, value2, "reserved02");
            return (Criteria) this;
        }

        public Criteria andReserved02NotBetween(String value1, String value2) {
            addCriterion("RESERVED_02 not between", value1, value2, "reserved02");
            return (Criteria) this;
        }

        public Criteria andTransferIdLikeInsensitive(String value) {
            addCriterion("upper(TRANSFER_ID) like", value.toUpperCase(), "transferId");
            return (Criteria) this;
        }

        public Criteria andSourceUserIdLikeInsensitive(String value) {
            addCriterion("upper(SOURCE_USER_ID) like", value.toUpperCase(), "sourceUserId");
            return (Criteria) this;
        }

        public Criteria andSourceAssetIdLikeInsensitive(String value) {
            addCriterion("upper(SOURCE_ASSET_ID) like", value.toUpperCase(), "sourceAssetId");
            return (Criteria) this;
        }

        public Criteria andSourceFundIdLikeInsensitive(String value) {
            addCriterion("upper(SOURCE_FUND_ID) like", value.toUpperCase(), "sourceFundId");
            return (Criteria) this;
        }

        public Criteria andTargetUserIdLikeInsensitive(String value) {
            addCriterion("upper(TARGET_USER_ID) like", value.toUpperCase(), "targetUserId");
            return (Criteria) this;
        }

        public Criteria andTargetAssetIdLikeInsensitive(String value) {
            addCriterion("upper(TARGET_ASSET_ID) like", value.toUpperCase(), "targetAssetId");
            return (Criteria) this;
        }

        public Criteria andTargetFundIdLikeInsensitive(String value) {
            addCriterion("upper(TARGET_FUND_ID) like", value.toUpperCase(), "targetFundId");
            return (Criteria) this;
        }

        public Criteria andTransferTypeLikeInsensitive(String value) {
            addCriterion("upper(TRANSFER_TYPE) like", value.toUpperCase(), "transferType");
            return (Criteria) this;
        }

        public Criteria andPendIdLikeInsensitive(String value) {
            addCriterion("upper(PEND_ID) like", value.toUpperCase(), "pendId");
            return (Criteria) this;
        }

        public Criteria andTransferStatusLikeInsensitive(String value) {
            addCriterion("upper(TRANSFER_STATUS) like", value.toUpperCase(), "transferStatus");
            return (Criteria) this;
        }

        public Criteria andReserved01LikeInsensitive(String value) {
            addCriterion("upper(RESERVED_01) like", value.toUpperCase(), "reserved01");
            return (Criteria) this;
        }

        public Criteria andReserved02LikeInsensitive(String value) {
            addCriterion("upper(RESERVED_02) like", value.toUpperCase(), "reserved02");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 01 14:31:14 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}