package org.fc.wlt.ordbgens.wlt.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.outils.serialize.UUIDGenerator;

@AllArgsConstructor
@NoArgsConstructor
public class WLTUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.USER_ID
     *
     * @return the value of WLT_USER.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.USER_ID
     *
     * @param userId the value for WLT_USER.USER_ID
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTUserKey other = (WLTUserKey) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}