package org.fc.wlt.ordbgens.wlt.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import onight.tfw.ojpa.api.annotations.Tab;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="WLT_USER")
@AllArgsConstructor
@NoArgsConstructor
public class WLTUser extends WLTUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.USER_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.USER_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.USER_PASSWD
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String userPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.CHECK_PHONE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String checkPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.CHECK_EMAIL
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String checkEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.USER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_USER.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.USER_CODE
     *
     * @return the value of WLT_USER.USER_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.USER_CODE
     *
     * @param userCode the value for WLT_USER.USER_CODE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.USER_NAME
     *
     * @return the value of WLT_USER.USER_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.USER_NAME
     *
     * @param userName the value for WLT_USER.USER_NAME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.USER_PASSWD
     *
     * @return the value of WLT_USER.USER_PASSWD
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getUserPasswd() {
        return userPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.USER_PASSWD
     *
     * @param userPasswd the value for WLT_USER.USER_PASSWD
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setUserPasswd(String userPasswd) {
        this.userPasswd = userPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.CHECK_PHONE
     *
     * @return the value of WLT_USER.CHECK_PHONE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getCheckPhone() {
        return checkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.CHECK_PHONE
     *
     * @param checkPhone the value for WLT_USER.CHECK_PHONE
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setCheckPhone(String checkPhone) {
        this.checkPhone = checkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.CHECK_EMAIL
     *
     * @return the value of WLT_USER.CHECK_EMAIL
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getCheckEmail() {
        return checkEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.CHECK_EMAIL
     *
     * @param checkEmail the value for WLT_USER.CHECK_EMAIL
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setCheckEmail(String checkEmail) {
        this.checkEmail = checkEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.USER_STATUS
     *
     * @return the value of WLT_USER.USER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.USER_STATUS
     *
     * @param userStatus the value for WLT_USER.USER_STATUS
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.CREATED_TIME
     *
     * @return the value of WLT_USER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.CREATED_TIME
     *
     * @param createdTime the value for WLT_USER.CREATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.UPDATED_TIME
     *
     * @return the value of WLT_USER.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.UPDATED_TIME
     *
     * @param updatedTime the value for WLT_USER.UPDATED_TIME
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.RESERVED1
     *
     * @return the value of WLT_USER.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.RESERVED1
     *
     * @param reserved1 the value for WLT_USER.RESERVED1
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_USER.RESERVED2
     *
     * @return the value of WLT_USER.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_USER.RESERVED2
     *
     * @param reserved2 the value for WLT_USER.RESERVED2
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WLTUser other = (WLTUser) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserCode() == null ? other.getUserCode() == null : this.getUserCode().equals(other.getUserCode()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserPasswd() == null ? other.getUserPasswd() == null : this.getUserPasswd().equals(other.getUserPasswd()))
            && (this.getCheckPhone() == null ? other.getCheckPhone() == null : this.getCheckPhone().equals(other.getCheckPhone()))
            && (this.getCheckEmail() == null ? other.getCheckEmail() == null : this.getCheckEmail().equals(other.getCheckEmail()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()))
            && (this.getReserved1() == null ? other.getReserved1() == null : this.getReserved1().equals(other.getReserved1()))
            && (this.getReserved2() == null ? other.getReserved2() == null : this.getReserved2().equals(other.getReserved2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserCode() == null) ? 0 : getUserCode().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserPasswd() == null) ? 0 : getUserPasswd().hashCode());
        result = prime * result + ((getCheckPhone() == null) ? 0 : getCheckPhone().hashCode());
        result = prime * result + ((getCheckEmail() == null) ? 0 : getCheckEmail().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        result = prime * result + ((getReserved1() == null) ? 0 : getReserved1().hashCode());
        result = prime * result + ((getReserved2() == null) ? 0 : getReserved2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userCode=").append(userCode);
        sb.append(", userName=").append(userName);
        sb.append(", userPasswd=").append(userPasswd);
        sb.append(", checkPhone=").append(checkPhone);
        sb.append(", checkEmail=").append(checkEmail);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", reserved1=").append(reserved1);
        sb.append(", reserved2=").append(reserved2);
        sb.append("]");
        return sb.toString();
    }
}