package org.fc.wlt.ordbgens.wlt.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.fc.wlt.ordbgens.wlt.entity.WLTAsset;
import org.fc.wlt.ordbgens.wlt.entity.WLTAssetExample.Criteria;
import org.fc.wlt.ordbgens.wlt.entity.WLTAssetExample.Criterion;
import org.fc.wlt.ordbgens.wlt.entity.WLTAssetExample;

public class WLTAssetSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String countByExample(WLTAssetExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("WLT_ASSET");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String deleteByExample(WLTAssetExample example) {
        BEGIN();
        DELETE_FROM("WLT_ASSET");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String insertSelective(WLTAsset record) {
        BEGIN();
        INSERT_INTO("WLT_ASSET");
        
        if (record.getAssetId() != null) {
            VALUES("ASSET_ID", "#{assetId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            VALUES("USER_ID", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getFundId() != null) {
            VALUES("FUND_ID", "#{fundId,jdbcType=VARCHAR}");
        }
        
        if (record.getHoldCount() != null) {
            VALUES("HOLD_COUNT", "#{holdCount,jdbcType=DOUBLE}");
        }
        
        if (record.getBcTxid() != null) {
            VALUES("BC_TXID", "#{bcTxid,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrId() != null) {
            VALUES("ADDR_ID", "#{addrId,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetPubHash() != null) {
            VALUES("ASSET_PUB_HASH", "#{assetPubHash,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetType() != null) {
            VALUES("ASSET_TYPE", "#{assetType,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetStatus() != null) {
            VALUES("ASSET_STATUS", "#{assetStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetAlias() != null) {
            VALUES("ASSET_ALIAS", "#{assetAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetKeywords() != null) {
            VALUES("ASSET_KEYWORDS", "#{assetKeywords,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtEname() != null) {
            VALUES("DMT_ENAME", "#{dmtEname,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtCname() != null) {
            VALUES("DMT_CNAME", "#{dmtCname,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtCount() != null) {
            VALUES("DMT_COUNT", "#{dmtCount,jdbcType=DOUBLE}");
        }
        
        if (record.getMetadata() != null) {
            VALUES("METADATA", "#{metadata,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            VALUES("CREATED_TIME", "#{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            VALUES("UPDATED_TIME", "#{updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            VALUES("RESERVED1", "#{reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            VALUES("RESERVED2", "#{reserved2,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String selectByExample(WLTAssetExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ASSET_ID");
        } else {
            SELECT("ASSET_ID");
        }
        SELECT("USER_ID");
        SELECT("FUND_ID");
        SELECT("HOLD_COUNT");
        SELECT("BC_TXID");
        SELECT("ADDR_ID");
        SELECT("ASSET_PUB_HASH");
        SELECT("ASSET_TYPE");
        SELECT("ASSET_STATUS");
        SELECT("ASSET_ALIAS");
        SELECT("ASSET_KEYWORDS");
        SELECT("DMT_ENAME");
        SELECT("DMT_CNAME");
        SELECT("DMT_COUNT");
        SELECT("METADATA");
        SELECT("CREATED_TIME");
        SELECT("UPDATED_TIME");
        SELECT("RESERVED1");
        SELECT("RESERVED2");
        FROM("WLT_ASSET");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("WLT_ASSET");				applyWhere(example, false);
		}
        if(example != null){
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >0 ){
                String retstr= SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return SQL()+"  FOR UPDATE " ;  }
            }
            return SQL();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        WLTAsset record = (WLTAsset) parameter.get("record");
        WLTAssetExample example = (WLTAssetExample) parameter.get("example");
        
        BEGIN();
        UPDATE("WLT_ASSET");
        
        if (record.getAssetId() != null) {
            SET("ASSET_ID = #{record.assetId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getFundId() != null) {
            SET("FUND_ID = #{record.fundId,jdbcType=VARCHAR}");
        }
        
        if (record.getHoldCount() != null) {
            SET("HOLD_COUNT = #{record.holdCount,jdbcType=DOUBLE}");
        }
        
        if (record.getBcTxid() != null) {
            SET("BC_TXID = #{record.bcTxid,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrId() != null) {
            SET("ADDR_ID = #{record.addrId,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetPubHash() != null) {
            SET("ASSET_PUB_HASH = #{record.assetPubHash,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetType() != null) {
            SET("ASSET_TYPE = #{record.assetType,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetStatus() != null) {
            SET("ASSET_STATUS = #{record.assetStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetAlias() != null) {
            SET("ASSET_ALIAS = #{record.assetAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetKeywords() != null) {
            SET("ASSET_KEYWORDS = #{record.assetKeywords,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtEname() != null) {
            SET("DMT_ENAME = #{record.dmtEname,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtCname() != null) {
            SET("DMT_CNAME = #{record.dmtCname,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtCount() != null) {
            SET("DMT_COUNT = #{record.dmtCount,jdbcType=DOUBLE}");
        }
        
        if (record.getMetadata() != null) {
            SET("METADATA = #{record.metadata,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("CREATED_TIME = #{record.createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            SET("UPDATED_TIME = #{record.updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            SET("RESERVED1 = #{record.reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            SET("RESERVED2 = #{record.reserved2,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("WLT_ASSET");
        
        SET("ASSET_ID = #{record.assetId,jdbcType=VARCHAR}");
        SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        SET("FUND_ID = #{record.fundId,jdbcType=VARCHAR}");
        SET("HOLD_COUNT = #{record.holdCount,jdbcType=DOUBLE}");
        SET("BC_TXID = #{record.bcTxid,jdbcType=VARCHAR}");
        SET("ADDR_ID = #{record.addrId,jdbcType=VARCHAR}");
        SET("ASSET_PUB_HASH = #{record.assetPubHash,jdbcType=VARCHAR}");
        SET("ASSET_TYPE = #{record.assetType,jdbcType=VARCHAR}");
        SET("ASSET_STATUS = #{record.assetStatus,jdbcType=VARCHAR}");
        SET("ASSET_ALIAS = #{record.assetAlias,jdbcType=VARCHAR}");
        SET("ASSET_KEYWORDS = #{record.assetKeywords,jdbcType=VARCHAR}");
        SET("DMT_ENAME = #{record.dmtEname,jdbcType=VARCHAR}");
        SET("DMT_CNAME = #{record.dmtCname,jdbcType=VARCHAR}");
        SET("DMT_COUNT = #{record.dmtCount,jdbcType=DOUBLE}");
        SET("METADATA = #{record.metadata,jdbcType=VARCHAR}");
        SET("CREATED_TIME = #{record.createdTime,jdbcType=TIMESTAMP}");
        SET("UPDATED_TIME = #{record.updatedTime,jdbcType=TIMESTAMP}");
        SET("RESERVED1 = #{record.reserved1,jdbcType=VARCHAR}");
        SET("RESERVED2 = #{record.reserved2,jdbcType=VARCHAR}");
        
        WLTAssetExample example = (WLTAssetExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String updateByPrimaryKeySelective(WLTAsset record) {
        BEGIN();
        UPDATE("WLT_ASSET");
        
        if (record.getUserId() != null) {
            SET("USER_ID = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getFundId() != null) {
            SET("FUND_ID = #{fundId,jdbcType=VARCHAR}");
        }
        
        if (record.getHoldCount() != null) {
            SET("HOLD_COUNT = #{holdCount,jdbcType=DOUBLE}");
        }
        
        if (record.getBcTxid() != null) {
            SET("BC_TXID = #{bcTxid,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrId() != null) {
            SET("ADDR_ID = #{addrId,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetPubHash() != null) {
            SET("ASSET_PUB_HASH = #{assetPubHash,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetType() != null) {
            SET("ASSET_TYPE = #{assetType,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetStatus() != null) {
            SET("ASSET_STATUS = #{assetStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetAlias() != null) {
            SET("ASSET_ALIAS = #{assetAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getAssetKeywords() != null) {
            SET("ASSET_KEYWORDS = #{assetKeywords,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtEname() != null) {
            SET("DMT_ENAME = #{dmtEname,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtCname() != null) {
            SET("DMT_CNAME = #{dmtCname,jdbcType=VARCHAR}");
        }
        
        if (record.getDmtCount() != null) {
            SET("DMT_COUNT = #{dmtCount,jdbcType=DOUBLE}");
        }
        
        if (record.getMetadata() != null) {
            SET("METADATA = #{metadata,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("CREATED_TIME = #{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            SET("UPDATED_TIME = #{updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            SET("RESERVED1 = #{reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            SET("RESERVED2 = #{reserved2,jdbcType=VARCHAR}");
        }
        
        WHERE("ASSET_ID = #{assetId,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ASSET
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected void applyWhere(WLTAssetExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}