package org.fc.wlt.ordbgens.wlt.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.fc.wlt.ordbgens.wlt.entity.WLTAddr;
import org.fc.wlt.ordbgens.wlt.entity.WLTAddrExample.Criteria;
import org.fc.wlt.ordbgens.wlt.entity.WLTAddrExample.Criterion;
import org.fc.wlt.ordbgens.wlt.entity.WLTAddrExample;

public class WLTAddrSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String countByExample(WLTAddrExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("WLT_ADDR");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String deleteByExample(WLTAddrExample example) {
        BEGIN();
        DELETE_FROM("WLT_ADDR");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String insertSelective(WLTAddr record) {
        BEGIN();
        INSERT_INTO("WLT_ADDR");
        
        if (record.getAddrId() != null) {
            VALUES("ADDR_ID", "#{addrId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            VALUES("USER_ID", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getHexAddr() != null) {
            VALUES("HEX_ADDR", "#{hexAddr,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKey() != null) {
            VALUES("PUBLIC_KEY", "#{publicKey,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKeyHash() != null) {
            VALUES("PUBLIC_KEY_HASH", "#{publicKeyHash,jdbcType=VARCHAR}");
        }
        
        if (record.getPrivateKey() != null) {
            VALUES("PRIVATE_KEY", "#{privateKey,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrStatus() != null) {
            VALUES("ADDR_STATUS", "#{addrStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            VALUES("CREATED_TIME", "#{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            VALUES("UPDATED_TIME", "#{updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            VALUES("RESERVED1", "#{reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            VALUES("RESERVED2", "#{reserved2,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String selectByExample(WLTAddrExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ADDR_ID");
        } else {
            SELECT("ADDR_ID");
        }
        SELECT("USER_ID");
        SELECT("HEX_ADDR");
        SELECT("PUBLIC_KEY");
        SELECT("PUBLIC_KEY_HASH");
        SELECT("PRIVATE_KEY");
        SELECT("ADDR_STATUS");
        SELECT("CREATED_TIME");
        SELECT("UPDATED_TIME");
        SELECT("RESERVED1");
        SELECT("RESERVED2");
        FROM("WLT_ADDR");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("WLT_ADDR");				applyWhere(example, false);
		}
        if(example != null){
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >0 ){
                String retstr= SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return SQL()+"  FOR UPDATE " ;  }
            }
            return SQL();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        WLTAddr record = (WLTAddr) parameter.get("record");
        WLTAddrExample example = (WLTAddrExample) parameter.get("example");
        
        BEGIN();
        UPDATE("WLT_ADDR");
        
        if (record.getAddrId() != null) {
            SET("ADDR_ID = #{record.addrId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getHexAddr() != null) {
            SET("HEX_ADDR = #{record.hexAddr,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKey() != null) {
            SET("PUBLIC_KEY = #{record.publicKey,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKeyHash() != null) {
            SET("PUBLIC_KEY_HASH = #{record.publicKeyHash,jdbcType=VARCHAR}");
        }
        
        if (record.getPrivateKey() != null) {
            SET("PRIVATE_KEY = #{record.privateKey,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrStatus() != null) {
            SET("ADDR_STATUS = #{record.addrStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("CREATED_TIME = #{record.createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            SET("UPDATED_TIME = #{record.updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            SET("RESERVED1 = #{record.reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            SET("RESERVED2 = #{record.reserved2,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("WLT_ADDR");
        
        SET("ADDR_ID = #{record.addrId,jdbcType=VARCHAR}");
        SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        SET("HEX_ADDR = #{record.hexAddr,jdbcType=VARCHAR}");
        SET("PUBLIC_KEY = #{record.publicKey,jdbcType=VARCHAR}");
        SET("PUBLIC_KEY_HASH = #{record.publicKeyHash,jdbcType=VARCHAR}");
        SET("PRIVATE_KEY = #{record.privateKey,jdbcType=VARCHAR}");
        SET("ADDR_STATUS = #{record.addrStatus,jdbcType=VARCHAR}");
        SET("CREATED_TIME = #{record.createdTime,jdbcType=TIMESTAMP}");
        SET("UPDATED_TIME = #{record.updatedTime,jdbcType=TIMESTAMP}");
        SET("RESERVED1 = #{record.reserved1,jdbcType=VARCHAR}");
        SET("RESERVED2 = #{record.reserved2,jdbcType=VARCHAR}");
        
        WLTAddrExample example = (WLTAddrExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    public String updateByPrimaryKeySelective(WLTAddr record) {
        BEGIN();
        UPDATE("WLT_ADDR");
        
        if (record.getUserId() != null) {
            SET("USER_ID = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getHexAddr() != null) {
            SET("HEX_ADDR = #{hexAddr,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKey() != null) {
            SET("PUBLIC_KEY = #{publicKey,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicKeyHash() != null) {
            SET("PUBLIC_KEY_HASH = #{publicKeyHash,jdbcType=VARCHAR}");
        }
        
        if (record.getPrivateKey() != null) {
            SET("PRIVATE_KEY = #{privateKey,jdbcType=VARCHAR}");
        }
        
        if (record.getAddrStatus() != null) {
            SET("ADDR_STATUS = #{addrStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("CREATED_TIME = #{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            SET("UPDATED_TIME = #{updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            SET("RESERVED1 = #{reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            SET("RESERVED2 = #{reserved2,jdbcType=VARCHAR}");
        }
        
        WHERE("ADDR_ID = #{addrId,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_ADDR
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    protected void applyWhere(WLTAddrExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}