package org.fc.wlt.ordbgens.wlt.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.fc.wlt.ordbgens.wlt.entity.WLTCertPer;
import org.fc.wlt.ordbgens.wlt.entity.WLTCertPerExample;
import org.fc.wlt.ordbgens.wlt.entity.WLTCertPerKey;

public interface WLTCertPerMapper extends StaticTableDaoSupport<WLTCertPer, WLTCertPerExample, WLTCertPerKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @SelectProvider(type=WLTCertPerSqlProvider.class, method="countByExample")
    int countByExample(WLTCertPerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @DeleteProvider(type=WLTCertPerSqlProvider.class, method="deleteByExample")
    int deleteByExample(WLTCertPerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Delete({
        "delete from WLT_CERT_PER",
        "where PER_ID = #{perId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(WLTCertPerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Insert({
        "insert into WLT_CERT_PER (PER_ID, PER_CODE, ",
        "USER_ID, REAL_NAME, ",
        "ID_CARD_TYPE, ID_CARD_CODE, ",
        "ID_CARD_PHOTO_ID, PER_STATUS, ",
        "CREATED_TIME, UPDATED_TIMD, ",
        "RESERVED1, RESERVED2)",
        "values (#{perId,jdbcType=VARCHAR}, #{perCode,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=VARCHAR}, #{realName,jdbcType=VARCHAR}, ",
        "#{idCardType,jdbcType=VARCHAR}, #{idCardCode,jdbcType=VARCHAR}, ",
        "#{idCardPhotoId,jdbcType=VARCHAR}, #{perStatus,jdbcType=VARCHAR}, ",
        "#{createdTime,jdbcType=TIMESTAMP}, #{updatedTimd,jdbcType=TIMESTAMP}, ",
        "#{reserved1,jdbcType=VARCHAR}, #{reserved2,jdbcType=VARCHAR})"
    })
    int insert(WLTCertPer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @InsertProvider(type=WLTCertPerSqlProvider.class, method="insertSelective")
    int insertSelective(WLTCertPer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @SelectProvider(type=WLTCertPerSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="PER_ID", property="perId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PER_CODE", property="perCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="REAL_NAME", property="realName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID_CARD_TYPE", property="idCardType", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID_CARD_CODE", property="idCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID_CARD_PHOTO_ID", property="idCardPhotoId", jdbcType=JdbcType.VARCHAR),
        @Result(column="PER_STATUS", property="perStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIMD", property="updatedTimd", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED1", property="reserved1", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED2", property="reserved2", jdbcType=JdbcType.VARCHAR)
    })
    List<WLTCertPer> selectByExample(WLTCertPerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Select({
        "select",
        "PER_ID, PER_CODE, USER_ID, REAL_NAME, ID_CARD_TYPE, ID_CARD_CODE, ID_CARD_PHOTO_ID, ",
        "PER_STATUS, CREATED_TIME, UPDATED_TIMD, RESERVED1, RESERVED2",
        "from WLT_CERT_PER",
        "where PER_ID = #{perId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="PER_ID", property="perId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PER_CODE", property="perCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="REAL_NAME", property="realName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID_CARD_TYPE", property="idCardType", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID_CARD_CODE", property="idCardCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID_CARD_PHOTO_ID", property="idCardPhotoId", jdbcType=JdbcType.VARCHAR),
        @Result(column="PER_STATUS", property="perStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIMD", property="updatedTimd", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED1", property="reserved1", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED2", property="reserved2", jdbcType=JdbcType.VARCHAR)
    })
    WLTCertPer selectByPrimaryKey(WLTCertPerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTCertPerSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WLTCertPer record, @Param("example") WLTCertPerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTCertPerSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WLTCertPer record, @Param("example") WLTCertPerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTCertPerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WLTCertPer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_PER
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Update({
        "update WLT_CERT_PER",
        "set PER_CODE = #{perCode,jdbcType=VARCHAR},",
          "USER_ID = #{userId,jdbcType=VARCHAR},",
          "REAL_NAME = #{realName,jdbcType=VARCHAR},",
          "ID_CARD_TYPE = #{idCardType,jdbcType=VARCHAR},",
          "ID_CARD_CODE = #{idCardCode,jdbcType=VARCHAR},",
          "ID_CARD_PHOTO_ID = #{idCardPhotoId,jdbcType=VARCHAR},",
          "PER_STATUS = #{perStatus,jdbcType=VARCHAR},",
          "CREATED_TIME = #{createdTime,jdbcType=TIMESTAMP},",
          "UPDATED_TIMD = #{updatedTimd,jdbcType=TIMESTAMP},",
          "RESERVED1 = #{reserved1,jdbcType=VARCHAR},",
          "RESERVED2 = #{reserved2,jdbcType=VARCHAR}",
        "where PER_ID = #{perId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WLTCertPer record);
}