package org.fc.wlt.ordbgens.wlt.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.fc.wlt.ordbgens.wlt.entity.WLTCertOrg;
import org.fc.wlt.ordbgens.wlt.entity.WLTCertOrgExample;
import org.fc.wlt.ordbgens.wlt.entity.WLTCertOrgKey;

public interface WLTCertOrgMapper extends StaticTableDaoSupport<WLTCertOrg, WLTCertOrgExample, WLTCertOrgKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @SelectProvider(type=WLTCertOrgSqlProvider.class, method="countByExample")
    int countByExample(WLTCertOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @DeleteProvider(type=WLTCertOrgSqlProvider.class, method="deleteByExample")
    int deleteByExample(WLTCertOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Delete({
        "delete from WLT_CERT_ORG",
        "where ORG_ID = #{orgId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(WLTCertOrgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Insert({
        "insert into WLT_CERT_ORG (ORG_ID, ORG_CODE, ",
        "ORG_NAME, ORG_TYPE, ",
        "USER_ID, CORPORATE_NAME, ",
        "LICENSE_CODE, LICENSE_PHOTO_ID, ",
        "NATIONAL, PROVINCE, ",
        "CITY, STREET, TEL, ",
        "FAX, WEB_RECORD_NUM, ",
        "ORG_STATUS, CREATED_TIME, ",
        "UPDATED_TIME, RESERVED1, ",
        "RESERVED2)",
        "values (#{orgId,jdbcType=VARCHAR}, #{orgCode,jdbcType=VARCHAR}, ",
        "#{orgName,jdbcType=VARCHAR}, #{orgType,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=VARCHAR}, #{corporateName,jdbcType=VARCHAR}, ",
        "#{licenseCode,jdbcType=VARCHAR}, #{licensePhotoId,jdbcType=VARCHAR}, ",
        "#{national,jdbcType=VARCHAR}, #{province,jdbcType=VARCHAR}, ",
        "#{city,jdbcType=VARCHAR}, #{street,jdbcType=VARCHAR}, #{tel,jdbcType=VARCHAR}, ",
        "#{fax,jdbcType=VARCHAR}, #{webRecordNum,jdbcType=VARCHAR}, ",
        "#{orgStatus,jdbcType=VARCHAR}, #{createdTime,jdbcType=TIMESTAMP}, ",
        "#{updatedTime,jdbcType=TIMESTAMP}, #{reserved1,jdbcType=VARCHAR}, ",
        "#{reserved2,jdbcType=VARCHAR})"
    })
    int insert(WLTCertOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @InsertProvider(type=WLTCertOrgSqlProvider.class, method="insertSelective")
    int insertSelective(WLTCertOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @SelectProvider(type=WLTCertOrgSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ORG_ID", property="orgId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CODE", property="orgCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_NAME", property="orgName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_TYPE", property="orgType", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CORPORATE_NAME", property="corporateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="LICENSE_CODE", property="licenseCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="LICENSE_PHOTO_ID", property="licensePhotoId", jdbcType=JdbcType.VARCHAR),
        @Result(column="NATIONAL", property="national", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET", property="street", jdbcType=JdbcType.VARCHAR),
        @Result(column="TEL", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="WEB_RECORD_NUM", property="webRecordNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_STATUS", property="orgStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIME", property="updatedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED1", property="reserved1", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED2", property="reserved2", jdbcType=JdbcType.VARCHAR)
    })
    List<WLTCertOrg> selectByExample(WLTCertOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Select({
        "select",
        "ORG_ID, ORG_CODE, ORG_NAME, ORG_TYPE, USER_ID, CORPORATE_NAME, LICENSE_CODE, ",
        "LICENSE_PHOTO_ID, NATIONAL, PROVINCE, CITY, STREET, TEL, FAX, WEB_RECORD_NUM, ",
        "ORG_STATUS, CREATED_TIME, UPDATED_TIME, RESERVED1, RESERVED2",
        "from WLT_CERT_ORG",
        "where ORG_ID = #{orgId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORG_ID", property="orgId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CODE", property="orgCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_NAME", property="orgName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_TYPE", property="orgType", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CORPORATE_NAME", property="corporateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="LICENSE_CODE", property="licenseCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="LICENSE_PHOTO_ID", property="licensePhotoId", jdbcType=JdbcType.VARCHAR),
        @Result(column="NATIONAL", property="national", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET", property="street", jdbcType=JdbcType.VARCHAR),
        @Result(column="TEL", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="WEB_RECORD_NUM", property="webRecordNum", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_STATUS", property="orgStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIME", property="updatedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED1", property="reserved1", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED2", property="reserved2", jdbcType=JdbcType.VARCHAR)
    })
    WLTCertOrg selectByPrimaryKey(WLTCertOrgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTCertOrgSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WLTCertOrg record, @Param("example") WLTCertOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTCertOrgSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WLTCertOrg record, @Param("example") WLTCertOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTCertOrgSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WLTCertOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_CERT_ORG
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Update({
        "update WLT_CERT_ORG",
        "set ORG_CODE = #{orgCode,jdbcType=VARCHAR},",
          "ORG_NAME = #{orgName,jdbcType=VARCHAR},",
          "ORG_TYPE = #{orgType,jdbcType=VARCHAR},",
          "USER_ID = #{userId,jdbcType=VARCHAR},",
          "CORPORATE_NAME = #{corporateName,jdbcType=VARCHAR},",
          "LICENSE_CODE = #{licenseCode,jdbcType=VARCHAR},",
          "LICENSE_PHOTO_ID = #{licensePhotoId,jdbcType=VARCHAR},",
          "NATIONAL = #{national,jdbcType=VARCHAR},",
          "PROVINCE = #{province,jdbcType=VARCHAR},",
          "CITY = #{city,jdbcType=VARCHAR},",
          "STREET = #{street,jdbcType=VARCHAR},",
          "TEL = #{tel,jdbcType=VARCHAR},",
          "FAX = #{fax,jdbcType=VARCHAR},",
          "WEB_RECORD_NUM = #{webRecordNum,jdbcType=VARCHAR},",
          "ORG_STATUS = #{orgStatus,jdbcType=VARCHAR},",
          "CREATED_TIME = #{createdTime,jdbcType=TIMESTAMP},",
          "UPDATED_TIME = #{updatedTime,jdbcType=TIMESTAMP},",
          "RESERVED1 = #{reserved1,jdbcType=VARCHAR},",
          "RESERVED2 = #{reserved2,jdbcType=VARCHAR}",
        "where ORG_ID = #{orgId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WLTCertOrg record);
}