package org.fc.wlt.ordbgens.wlt.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.fc.wlt.ordbgens.wlt.entity.WLTFund;
import org.fc.wlt.ordbgens.wlt.entity.WLTFundExample;
import org.fc.wlt.ordbgens.wlt.entity.WLTFundKey;

public interface WLTFundMapper extends StaticTableDaoSupport<WLTFund, WLTFundExample, WLTFundKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @SelectProvider(type=WLTFundSqlProvider.class, method="countByExample")
    int countByExample(WLTFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @DeleteProvider(type=WLTFundSqlProvider.class, method="deleteByExample")
    int deleteByExample(WLTFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Delete({
        "delete from WLT_FUND",
        "where FUND_ID = #{fundId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(WLTFundKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Insert({
        "insert into WLT_FUND (FUND_ID, USER_ID, ",
        "DMT_CNAME, DMT_ENAME, ",
        "GENIS_ADDR, GENIS_ORG_ID, ",
        "GENIS_DEPOSIT, TOTAL_COUNT, ",
        "COLORED_FBC, EXCHANGE_FBC, ",
        "TURNOVER_COUNT, DATE_TIME, ",
        "FUND_STATUS, CREATED_TIME, ",
        "UPDATED_TIME, RESERVED1, ",
        "RESERVED2)",
        "values (#{fundId,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{dmtCname,jdbcType=VARCHAR}, #{dmtEname,jdbcType=VARCHAR}, ",
        "#{genisAddr,jdbcType=VARCHAR}, #{genisOrgId,jdbcType=VARCHAR}, ",
        "#{genisDeposit,jdbcType=DOUBLE}, #{totalCount,jdbcType=DOUBLE}, ",
        "#{coloredFbc,jdbcType=DOUBLE}, #{exchangeFbc,jdbcType=DOUBLE}, ",
        "#{turnoverCount,jdbcType=DOUBLE}, #{dateTime,jdbcType=TIMESTAMP}, ",
        "#{fundStatus,jdbcType=VARCHAR}, #{createdTime,jdbcType=TIMESTAMP}, ",
        "#{updatedTime,jdbcType=TIMESTAMP}, #{reserved1,jdbcType=VARCHAR}, ",
        "#{reserved2,jdbcType=VARCHAR})"
    })
    int insert(WLTFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @InsertProvider(type=WLTFundSqlProvider.class, method="insertSelective")
    int insertSelective(WLTFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @SelectProvider(type=WLTFundSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="FUND_ID", property="fundId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="DMT_CNAME", property="dmtCname", jdbcType=JdbcType.VARCHAR),
        @Result(column="DMT_ENAME", property="dmtEname", jdbcType=JdbcType.VARCHAR),
        @Result(column="GENIS_ADDR", property="genisAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="GENIS_ORG_ID", property="genisOrgId", jdbcType=JdbcType.VARCHAR),
        @Result(column="GENIS_DEPOSIT", property="genisDeposit", jdbcType=JdbcType.DOUBLE),
        @Result(column="TOTAL_COUNT", property="totalCount", jdbcType=JdbcType.DOUBLE),
        @Result(column="COLORED_FBC", property="coloredFbc", jdbcType=JdbcType.DOUBLE),
        @Result(column="EXCHANGE_FBC", property="exchangeFbc", jdbcType=JdbcType.DOUBLE),
        @Result(column="TURNOVER_COUNT", property="turnoverCount", jdbcType=JdbcType.DOUBLE),
        @Result(column="DATE_TIME", property="dateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FUND_STATUS", property="fundStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIME", property="updatedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED1", property="reserved1", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED2", property="reserved2", jdbcType=JdbcType.VARCHAR)
    })
    List<WLTFund> selectByExample(WLTFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Select({
        "select",
        "FUND_ID, USER_ID, DMT_CNAME, DMT_ENAME, GENIS_ADDR, GENIS_ORG_ID, GENIS_DEPOSIT, ",
        "TOTAL_COUNT, COLORED_FBC, EXCHANGE_FBC, TURNOVER_COUNT, DATE_TIME, FUND_STATUS, ",
        "CREATED_TIME, UPDATED_TIME, RESERVED1, RESERVED2",
        "from WLT_FUND",
        "where FUND_ID = #{fundId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="FUND_ID", property="fundId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="DMT_CNAME", property="dmtCname", jdbcType=JdbcType.VARCHAR),
        @Result(column="DMT_ENAME", property="dmtEname", jdbcType=JdbcType.VARCHAR),
        @Result(column="GENIS_ADDR", property="genisAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="GENIS_ORG_ID", property="genisOrgId", jdbcType=JdbcType.VARCHAR),
        @Result(column="GENIS_DEPOSIT", property="genisDeposit", jdbcType=JdbcType.DOUBLE),
        @Result(column="TOTAL_COUNT", property="totalCount", jdbcType=JdbcType.DOUBLE),
        @Result(column="COLORED_FBC", property="coloredFbc", jdbcType=JdbcType.DOUBLE),
        @Result(column="EXCHANGE_FBC", property="exchangeFbc", jdbcType=JdbcType.DOUBLE),
        @Result(column="TURNOVER_COUNT", property="turnoverCount", jdbcType=JdbcType.DOUBLE),
        @Result(column="DATE_TIME", property="dateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="FUND_STATUS", property="fundStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIME", property="updatedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED1", property="reserved1", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED2", property="reserved2", jdbcType=JdbcType.VARCHAR)
    })
    WLTFund selectByPrimaryKey(WLTFundKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTFundSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WLTFund record, @Param("example") WLTFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTFundSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WLTFund record, @Param("example") WLTFundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTFundSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WLTFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FUND
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Update({
        "update WLT_FUND",
        "set USER_ID = #{userId,jdbcType=VARCHAR},",
          "DMT_CNAME = #{dmtCname,jdbcType=VARCHAR},",
          "DMT_ENAME = #{dmtEname,jdbcType=VARCHAR},",
          "GENIS_ADDR = #{genisAddr,jdbcType=VARCHAR},",
          "GENIS_ORG_ID = #{genisOrgId,jdbcType=VARCHAR},",
          "GENIS_DEPOSIT = #{genisDeposit,jdbcType=DOUBLE},",
          "TOTAL_COUNT = #{totalCount,jdbcType=DOUBLE},",
          "COLORED_FBC = #{coloredFbc,jdbcType=DOUBLE},",
          "EXCHANGE_FBC = #{exchangeFbc,jdbcType=DOUBLE},",
          "TURNOVER_COUNT = #{turnoverCount,jdbcType=DOUBLE},",
          "DATE_TIME = #{dateTime,jdbcType=TIMESTAMP},",
          "FUND_STATUS = #{fundStatus,jdbcType=VARCHAR},",
          "CREATED_TIME = #{createdTime,jdbcType=TIMESTAMP},",
          "UPDATED_TIME = #{updatedTime,jdbcType=TIMESTAMP},",
          "RESERVED1 = #{reserved1,jdbcType=VARCHAR},",
          "RESERVED2 = #{reserved2,jdbcType=VARCHAR}",
        "where FUND_ID = #{fundId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WLTFund record);
}