package org.fc.wlt.ordbgens.wlt.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.fc.wlt.ordbgens.wlt.entity.WLTFile;
import org.fc.wlt.ordbgens.wlt.entity.WLTFileExample;
import org.fc.wlt.ordbgens.wlt.entity.WLTFileKey;

public interface WLTFileMapper extends StaticTableDaoSupport<WLTFile, WLTFileExample, WLTFileKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @SelectProvider(type=WLTFileSqlProvider.class, method="countByExample")
    int countByExample(WLTFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @DeleteProvider(type=WLTFileSqlProvider.class, method="deleteByExample")
    int deleteByExample(WLTFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Delete({
        "delete from WLT_FILE",
        "where FILE_ID = #{fileId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(WLTFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Insert({
        "insert into WLT_FILE (FILE_ID, FILE_PATH, ",
        "FILE_NAME, FILE_SIZE, ",
        "USER_ID, FILE_HASH, ",
        "CREATED_TIME, UPDATED_TIME, ",
        "RESERVED1, RESERVED2)",
        "values (#{fileId,jdbcType=VARCHAR}, #{filePath,jdbcType=VARCHAR}, ",
        "#{fileName,jdbcType=VARCHAR}, #{fileSize,jdbcType=DOUBLE}, ",
        "#{userId,jdbcType=VARCHAR}, #{fileHash,jdbcType=VARCHAR}, ",
        "#{createdTime,jdbcType=TIMESTAMP}, #{updatedTime,jdbcType=TIMESTAMP}, ",
        "#{reserved1,jdbcType=VARCHAR}, #{reserved2,jdbcType=VARCHAR})"
    })
    int insert(WLTFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @InsertProvider(type=WLTFileSqlProvider.class, method="insertSelective")
    int insertSelective(WLTFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @SelectProvider(type=WLTFileSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="FILE_ID", property="fileId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="FILE_PATH", property="filePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_NAME", property="fileName", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_SIZE", property="fileSize", jdbcType=JdbcType.DOUBLE),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_HASH", property="fileHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIME", property="updatedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED1", property="reserved1", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED2", property="reserved2", jdbcType=JdbcType.VARCHAR)
    })
    List<WLTFile> selectByExample(WLTFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Select({
        "select",
        "FILE_ID, FILE_PATH, FILE_NAME, FILE_SIZE, USER_ID, FILE_HASH, CREATED_TIME, ",
        "UPDATED_TIME, RESERVED1, RESERVED2",
        "from WLT_FILE",
        "where FILE_ID = #{fileId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="FILE_ID", property="fileId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="FILE_PATH", property="filePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_NAME", property="fileName", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_SIZE", property="fileSize", jdbcType=JdbcType.DOUBLE),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILE_HASH", property="fileHash", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIME", property="updatedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED1", property="reserved1", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED2", property="reserved2", jdbcType=JdbcType.VARCHAR)
    })
    WLTFile selectByPrimaryKey(WLTFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTFileSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WLTFile record, @Param("example") WLTFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTFileSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WLTFile record, @Param("example") WLTFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @UpdateProvider(type=WLTFileSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WLTFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_FILE
     *
     * @mbggenerated Thu Feb 01 14:31:13 CST 2018
     */
    @Update({
        "update WLT_FILE",
        "set FILE_PATH = #{filePath,jdbcType=VARCHAR},",
          "FILE_NAME = #{fileName,jdbcType=VARCHAR},",
          "FILE_SIZE = #{fileSize,jdbcType=DOUBLE},",
          "USER_ID = #{userId,jdbcType=VARCHAR},",
          "FILE_HASH = #{fileHash,jdbcType=VARCHAR},",
          "CREATED_TIME = #{createdTime,jdbcType=TIMESTAMP},",
          "UPDATED_TIME = #{updatedTime,jdbcType=TIMESTAMP},",
          "RESERVED1 = #{reserved1,jdbcType=VARCHAR},",
          "RESERVED2 = #{reserved2,jdbcType=VARCHAR}",
        "where FILE_ID = #{fileId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WLTFile record);
}