package org.fc.wlt.ordbgens.wlt.mapper;

import java.util.List;
import onight.tfw.ojpa.ordb.StaticTableDaoSupport;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.fc.wlt.ordbgens.wlt.entity.WLTTransfer;
import org.fc.wlt.ordbgens.wlt.entity.WLTTransferExample;
import org.fc.wlt.ordbgens.wlt.entity.WLTTransferKey;

public interface WLTTransferMapper extends StaticTableDaoSupport<WLTTransfer, WLTTransferExample, WLTTransferKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @SelectProvider(type=WLTTransferSqlProvider.class, method="countByExample")
    int countByExample(WLTTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @DeleteProvider(type=WLTTransferSqlProvider.class, method="deleteByExample")
    int deleteByExample(WLTTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Delete({
        "delete from WLT_TRANSFER",
        "where TRANSFER_ID = #{transferId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(WLTTransferKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Insert({
        "insert into WLT_TRANSFER (TRANSFER_ID, SOURCE_USER_ID, ",
        "SOURCE_ASSET_ID, SOURCE_AMOUNT, ",
        "SOURCE_FUND_ID, TARGET_USER_ID, ",
        "TARGET_ASSET_ID, TARGET_AMOUNT, ",
        "TARGET_FUND_ID, TOTAL_FEE, ",
        "TRANSFER_TYPE, PEND_ID, ",
        "TRANSFER_STATUS, CREATED_TIME, ",
        "UPDATED_TIME, RESERVED_01, ",
        "RESERVED_02)",
        "values (#{transferId,jdbcType=VARCHAR}, #{sourceUserId,jdbcType=VARCHAR}, ",
        "#{sourceAssetId,jdbcType=VARCHAR}, #{sourceAmount,jdbcType=DOUBLE}, ",
        "#{sourceFundId,jdbcType=VARCHAR}, #{targetUserId,jdbcType=VARCHAR}, ",
        "#{targetAssetId,jdbcType=VARCHAR}, #{targetAmount,jdbcType=DOUBLE}, ",
        "#{targetFundId,jdbcType=VARCHAR}, #{totalFee,jdbcType=DOUBLE}, ",
        "#{transferType,jdbcType=VARCHAR}, #{pendId,jdbcType=VARCHAR}, ",
        "#{transferStatus,jdbcType=VARCHAR}, #{createdTime,jdbcType=TIMESTAMP}, ",
        "#{updatedTime,jdbcType=TIMESTAMP}, #{reserved01,jdbcType=VARCHAR}, ",
        "#{reserved02,jdbcType=VARCHAR})"
    })
    int insert(WLTTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @InsertProvider(type=WLTTransferSqlProvider.class, method="insertSelective")
    int insertSelective(WLTTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @SelectProvider(type=WLTTransferSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="TRANSFER_ID", property="transferId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SOURCE_USER_ID", property="sourceUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="SOURCE_ASSET_ID", property="sourceAssetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="SOURCE_AMOUNT", property="sourceAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="SOURCE_FUND_ID", property="sourceFundId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGET_USER_ID", property="targetUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGET_ASSET_ID", property="targetAssetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGET_AMOUNT", property="targetAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="TARGET_FUND_ID", property="targetFundId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TOTAL_FEE", property="totalFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="TRANSFER_TYPE", property="transferType", jdbcType=JdbcType.VARCHAR),
        @Result(column="PEND_ID", property="pendId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSFER_STATUS", property="transferStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIME", property="updatedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED_01", property="reserved01", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED_02", property="reserved02", jdbcType=JdbcType.VARCHAR)
    })
    List<WLTTransfer> selectByExample(WLTTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Select({
        "select",
        "TRANSFER_ID, SOURCE_USER_ID, SOURCE_ASSET_ID, SOURCE_AMOUNT, SOURCE_FUND_ID, ",
        "TARGET_USER_ID, TARGET_ASSET_ID, TARGET_AMOUNT, TARGET_FUND_ID, TOTAL_FEE, TRANSFER_TYPE, ",
        "PEND_ID, TRANSFER_STATUS, CREATED_TIME, UPDATED_TIME, RESERVED_01, RESERVED_02",
        "from WLT_TRANSFER",
        "where TRANSFER_ID = #{transferId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="TRANSFER_ID", property="transferId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SOURCE_USER_ID", property="sourceUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="SOURCE_ASSET_ID", property="sourceAssetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="SOURCE_AMOUNT", property="sourceAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="SOURCE_FUND_ID", property="sourceFundId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGET_USER_ID", property="targetUserId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGET_ASSET_ID", property="targetAssetId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TARGET_AMOUNT", property="targetAmount", jdbcType=JdbcType.DOUBLE),
        @Result(column="TARGET_FUND_ID", property="targetFundId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TOTAL_FEE", property="totalFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="TRANSFER_TYPE", property="transferType", jdbcType=JdbcType.VARCHAR),
        @Result(column="PEND_ID", property="pendId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSFER_STATUS", property="transferStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TIME", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATED_TIME", property="updatedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RESERVED_01", property="reserved01", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESERVED_02", property="reserved02", jdbcType=JdbcType.VARCHAR)
    })
    WLTTransfer selectByPrimaryKey(WLTTransferKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @UpdateProvider(type=WLTTransferSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WLTTransfer record, @Param("example") WLTTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @UpdateProvider(type=WLTTransferSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WLTTransfer record, @Param("example") WLTTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @UpdateProvider(type=WLTTransferSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WLTTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_TRANSFER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    @Update({
        "update WLT_TRANSFER",
        "set SOURCE_USER_ID = #{sourceUserId,jdbcType=VARCHAR},",
          "SOURCE_ASSET_ID = #{sourceAssetId,jdbcType=VARCHAR},",
          "SOURCE_AMOUNT = #{sourceAmount,jdbcType=DOUBLE},",
          "SOURCE_FUND_ID = #{sourceFundId,jdbcType=VARCHAR},",
          "TARGET_USER_ID = #{targetUserId,jdbcType=VARCHAR},",
          "TARGET_ASSET_ID = #{targetAssetId,jdbcType=VARCHAR},",
          "TARGET_AMOUNT = #{targetAmount,jdbcType=DOUBLE},",
          "TARGET_FUND_ID = #{targetFundId,jdbcType=VARCHAR},",
          "TOTAL_FEE = #{totalFee,jdbcType=DOUBLE},",
          "TRANSFER_TYPE = #{transferType,jdbcType=VARCHAR},",
          "PEND_ID = #{pendId,jdbcType=VARCHAR},",
          "TRANSFER_STATUS = #{transferStatus,jdbcType=VARCHAR},",
          "CREATED_TIME = #{createdTime,jdbcType=TIMESTAMP},",
          "UPDATED_TIME = #{updatedTime,jdbcType=TIMESTAMP},",
          "RESERVED_01 = #{reserved01,jdbcType=VARCHAR},",
          "RESERVED_02 = #{reserved02,jdbcType=VARCHAR}",
        "where TRANSFER_ID = #{transferId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WLTTransfer record);
}