package org.fc.wlt.ordbgens.wlt.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.fc.wlt.ordbgens.wlt.entity.WLTUser;
import org.fc.wlt.ordbgens.wlt.entity.WLTUserExample.Criteria;
import org.fc.wlt.ordbgens.wlt.entity.WLTUserExample.Criterion;
import org.fc.wlt.ordbgens.wlt.entity.WLTUserExample;

public class WLTUserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String countByExample(WLTUserExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("WLT_USER");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String deleteByExample(WLTUserExample example) {
        BEGIN();
        DELETE_FROM("WLT_USER");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String insertSelective(WLTUser record) {
        BEGIN();
        INSERT_INTO("WLT_USER");
        
        if (record.getUserId() != null) {
            VALUES("USER_ID", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserCode() != null) {
            VALUES("USER_CODE", "#{userCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            VALUES("USER_NAME", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPasswd() != null) {
            VALUES("USER_PASSWD", "#{userPasswd,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckPhone() != null) {
            VALUES("CHECK_PHONE", "#{checkPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckEmail() != null) {
            VALUES("CHECK_EMAIL", "#{checkEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserStatus() != null) {
            VALUES("USER_STATUS", "#{userStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            VALUES("CREATED_TIME", "#{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            VALUES("UPDATED_TIME", "#{updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            VALUES("RESERVED1", "#{reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            VALUES("RESERVED2", "#{reserved2,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String selectByExample(WLTUserExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("USER_ID");
        } else {
            SELECT("USER_ID");
        }
        SELECT("USER_CODE");
        SELECT("USER_NAME");
        SELECT("USER_PASSWD");
        SELECT("CHECK_PHONE");
        SELECT("CHECK_EMAIL");
        SELECT("USER_STATUS");
        SELECT("CREATED_TIME");
        SELECT("UPDATED_TIME");
        SELECT("RESERVED1");
        SELECT("RESERVED2");
        FROM("WLT_USER");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example!=null&&example.getSelectCols()!=null&&example.getSelectCols().trim().length()>0){
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT(example.getSelectCols());
		} else {
				SELECT(example.getSelectCols());
		}
				FROM("WLT_USER");				applyWhere(example, false);
		}
        if(example != null){
            if(example.getLimit() !=  Integer.MAX_VALUE && example.getOffset() >0 ){
                String retstr= SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
                if(example.isForUpdate()) { return retstr+"  FOR UPDATE " ;} else { return retstr;}}
                else if(example.isForUpdate()){  return SQL()+"  FOR UPDATE " ;  }
            }
            return SQL();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        WLTUser record = (WLTUser) parameter.get("record");
        WLTUserExample example = (WLTUserExample) parameter.get("example");
        
        BEGIN();
        UPDATE("WLT_USER");
        
        if (record.getUserId() != null) {
            SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserCode() != null) {
            SET("USER_CODE = #{record.userCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            SET("USER_NAME = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPasswd() != null) {
            SET("USER_PASSWD = #{record.userPasswd,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckPhone() != null) {
            SET("CHECK_PHONE = #{record.checkPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckEmail() != null) {
            SET("CHECK_EMAIL = #{record.checkEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserStatus() != null) {
            SET("USER_STATUS = #{record.userStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("CREATED_TIME = #{record.createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            SET("UPDATED_TIME = #{record.updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            SET("RESERVED1 = #{record.reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            SET("RESERVED2 = #{record.reserved2,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("WLT_USER");
        
        SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        SET("USER_CODE = #{record.userCode,jdbcType=VARCHAR}");
        SET("USER_NAME = #{record.userName,jdbcType=VARCHAR}");
        SET("USER_PASSWD = #{record.userPasswd,jdbcType=VARCHAR}");
        SET("CHECK_PHONE = #{record.checkPhone,jdbcType=VARCHAR}");
        SET("CHECK_EMAIL = #{record.checkEmail,jdbcType=VARCHAR}");
        SET("USER_STATUS = #{record.userStatus,jdbcType=VARCHAR}");
        SET("CREATED_TIME = #{record.createdTime,jdbcType=TIMESTAMP}");
        SET("UPDATED_TIME = #{record.updatedTime,jdbcType=TIMESTAMP}");
        SET("RESERVED1 = #{record.reserved1,jdbcType=VARCHAR}");
        SET("RESERVED2 = #{record.reserved2,jdbcType=VARCHAR}");
        
        WLTUserExample example = (WLTUserExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    public String updateByPrimaryKeySelective(WLTUser record) {
        BEGIN();
        UPDATE("WLT_USER");
        
        if (record.getUserCode() != null) {
            SET("USER_CODE = #{userCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            SET("USER_NAME = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPasswd() != null) {
            SET("USER_PASSWD = #{userPasswd,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckPhone() != null) {
            SET("CHECK_PHONE = #{checkPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckEmail() != null) {
            SET("CHECK_EMAIL = #{checkEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserStatus() != null) {
            SET("USER_STATUS = #{userStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            SET("CREATED_TIME = #{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedTime() != null) {
            SET("UPDATED_TIME = #{updatedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getReserved1() != null) {
            SET("RESERVED1 = #{reserved1,jdbcType=VARCHAR}");
        }
        
        if (record.getReserved2() != null) {
            SET("RESERVED2 = #{reserved2,jdbcType=VARCHAR}");
        }
        
        WHERE("USER_ID = #{userId,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_USER
     *
     * @mbggenerated Thu Feb 01 14:31:14 CST 2018
     */
    protected void applyWhere(WLTUserExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}